export const AirLineIATACode = [
  "04",
  "0A",
  "0B",
  "0D",
  "0J",
  "1A",
  "1B",
  "1C",
  "1D",
  "1E",
  "1F",
  "1G",
  "1H",
  "1I",
  "1K",
  "1L",
  "1M",
  "1N",
  "1P",
  "1Q",
  "1R",
  "1S",
  "1T",
  "1U",
  "1W",
  "1Z",
  "20",
  "2A",
  "2B",
  "2C",
  "2D",
  "2F",
  "2G",
  "2H",
  "2J",
  "2K",
  "2L",
  "2M",
  "2N",
  "2O",
  "2P",
  "2Q",
  "2R",
  "2S",
  "2T",
  "2U",
  "2V",
  "2W",
  "2Z",
  "3C",
  "3G",
  "3J",
  "3K",
  "3L",
  "3N",
  "3P",
  "3Q",
  "3R",
  "3S",
  "3T",
  "3U",
  "3V",
  "3W",
  "4A",
  "4C",
  "4D",
  "4F",
  "4G",
  "4K",
  "4M",
  "4N",
  "4R",
  "4S",
  "4T",
  "4U",
  "4Y",
  "5A",
  "5C",
  "5D",
  "5F",
  "5G",
  "5J",
  "5K",
  "5L",
  "5M",
  "5N",
  "5T",
  "5V",
  "5W",
  "5X",
  "5Y",
  "5Z",
  "6A",
  "6B",
  "6E",
  "6G",
  "6H",
  "6I",
  "6J",
  "6K",
  "6N",
  "6P",
  "6Q",
  "6R",
  "6T",
  "6U",
  "6V",
  "6W",
  "6Z",
  "7A",
  "7B",
  "7C",
  "7E",
  "7F",
  "7G",
  "7K",
  "7L",
  "7N",
  "7O",
  "7P",
  "7R",
  "7T",
  "7W",
  "8A",
  "8B",
  "8C",
  "8D",
  "8E",
  "8F",
  "8H",
  "8I",
  "8J",
  "8L",
  "8M",
  "8N",
  "8O",
  "8P",
  "8Q",
  "8R",
  "8S",
  "8T",
  "8U",
  "8V",
  "8W",
  "8Y",
  "8z",
  "9E",
  "9I",
  "9K",
  "9L",
  "9O",
  "9Q",
  "9R",
  "9S",
  "9T",
  "9U",
  "9W",
  "9X",
  "9Y",
  "A2",
  "A3",
  "A4",
  "A5",
  "A6",
  "A7",
  "A8",
  "A9",
  "AA",
  "AB",
  "AC",
  "AD",
  "AE",
  "AF",
  "AG",
  "AH",
  "AI",
  "AJ",
  "AK",
  "AL",
  "AM",
  "AN",
  "AO",
  "AP",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AV",
  "AW",
  "AX",
  "AY",
  "AZ",
  "B2",
  "B3",
  "B4",
  "B5",
  "B6",
  "B8",
  "B9",
  "BA",
  "BB",
  "BC",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BK",
  "BL",
  "BM",
  "BN",
  "BO",
  "BP",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BU",
  "BV",
  "BW",
  "BX",
  "BY",
  "BZ",
  "C0",
  "C3",
  "C4",
  "C5",
  "C6",
  "C7",
  "C8",
  "C9",
  "CA",
  "CC",
  "CD",
  "CE",
  "CF",
  "CG",
  "CH",
  "CI",
  "CJ",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CP",
  "CQ",
  "CR",
  "CS",
  "CT",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "D3",
  "D4",
  "D5",
  "D6",
  "D7",
  "D8",
  "D9",
  "DA",
  "DB",
  "DC",
  "DD",
  "DE",
  "DG",
  "DH",
  "DI",
  "DJ",
  "DK",
  "DL",
  "DM",
  "DO",
  "DP",
  "DQ",
  "DR",
  "DT",
  "DU",
  "DV",
  "DW",
  "DX",
  "DY",
  "E0",
  "E2",
  "E3",
  "E4",
  "E5",
  "E6",
  "E7",
  "E8",
  "E9",
  "EA",
  "EC",
  "ED",
  "EE",
  "EF",
  "EG",
  "EH",
  "EI",
  "EJ",
  "EK",
  "EL",
  "EM",
  "EN",
  "EO",
  "EP",
  "EQ",
  "ER",
  "ES",
  "ET",
  "EU",
  "EV",
  "EW",
  "EX",
  "EY",
  "EZ",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F9",
  "FA",
  "FB",
  "FC",
  "FD",
  "FE",
  "FF",
  "FG",
  "FH",
  "FI",
  "FJ",
  "FK",
  "FL",
  "FM",
  "FN",
  "FO",
  "FP",
  "FQ",
  "FR",
  "FS",
  "FT",
  "FV",
  "FW",
  "FX",
  "FY",
  "G0",
  "G1",
  "G2",
  "G3",
  "G4",
  "G6",
  "G7",
  "G8",
  "G9",
  "GA",
  "GB",
  "GC",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GJ",
  "GK",
  "GL",
  "GM",
  "GN",
  "GO",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GV",
  "GW",
  "GX",
  "GY",
  "GZ",
  "H2",
  "H4",
  "H5",
  "H6",
  "H7",
  "H8",
  "H9",
  "HA",
  "HB",
  "HC",
  "HD",
  "HE",
  "HF",
  "HG",
  "HH",
  "HJ",
  "HK",
  "HM",
  "HN",
  "HO",
  "HP",
  "HQ",
  "HR",
  "HT",
  "HU",
  "HV",
  "HW",
  "HY",
  "HZ",
  "I4",
  "I6",
  "I7",
  "I9",
  "IA",
  "IB",
  "IC",
  "ID",
  "IE",
  "IF",
  "IG",
  "IH",
  "II",
  "IJ",
  "IK",
  "IM",
  "IN",
  "IO",
  "IP",
  "IQ",
  "IR",
  "IS",
  "IT",
  "IV",
  "IW",
  "IX",
  "IY",
  "IZ",
  "J2",
  "J3",
  "J4",
  "J6",
  "J7",
  "J8",
  "J9",
  "JA",
  "JB",
  "JC",
  "JE",
  "JF",
  "JH",
  "JI",
  "JJ",
  "JK",
  "JL",
  "JM",
  "JN",
  "JO",
  "JP",
  "JQ",
  "JR",
  "JS",
  "JT",
  "JU",
  "JV",
  "JW",
  "JX",
  "JY",
  "JZ",
  "K2",
  "K4",
  "K5",
  "K6",
  "K8",
  "K9",
  "KA",
  "KB",
  "KC",
  "KD",
  "KE",
  "KF",
  "KG",
  "KI",
  "KJ",
  "KK",
  "KL",
  "KM",
  "KO",
  "KP",
  "KQ",
  "KR",
  "KS",
  "KU",
  "KV",
  "KX",
  "KY",
  "KZ",
  "L1",
  "L2",
  "L3",
  "L5",
  "L6",
  "L7",
  "L8",
  "L9",
  "LA",
  "LB",
  "LC",
  "LD",
  "LF",
  "LG",
  "LH",
  "LI",
  "LJ",
  "LK",
  "LL",
  "LM",
  "LN",
  "LO",
  "LP",
  "LQ",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LW",
  "LX",
  "LY",
  "LZ",
  "M2",
  "M3",
  "M4",
  "M5",
  "M6",
  "M7",
  "M9",
  "MA",
  "MB",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MI",
  "MJ",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "N2",
  "N3",
  "N4",
  "N5",
  "N6",
  "N7",
  "N8",
  "N9",
  "NA",
  "NB",
  "NC",
  "NE",
  "NF",
  "NG",
  "NH",
  "NI",
  "NK",
  "NL",
  "NM",
  "NN",
  "NO",
  "NQ",
  "NR",
  "NT",
  "NU",
  "NV",
  "NW",
  "NX",
  "NY",
  "NZ",
  "O2",
  "O6",
  "O7",
  "O8",
  "OA",
  "OB",
  "OE",
  "OF",
  "OH",
  "OJ",
  "OK",
  "OL",
  "OM",
  "ON",
  "OO",
  "OP",
  "OR",
  "OS",
  "OT",
  "OU",
  "OV",
  "OW",
  "OX",
  "OY",
  "OZ",
  "P0",
  "P5",
  "P7",
  "P8",
  "P9",
  "PA",
  "PC",
  "PD",
  "PE",
  "PF",
  "PG",
  "PH",
  "PI",
  "PJ",
  "PK",
  "PL",
  "PM",
  "PN",
  "PO",
  "PQ",
  "PR",
  "PS",
  "PT",
  "PU",
  "PV",
  "PW",
  "PX",
  "PY",
  "PZ",
  "Q3",
  "Q4",
  "Q5",
  "Q6",
  "Q8",
  "Q9",
  "QB",
  "QC",
  "QD",
  "QE",
  "QF",
  "QH",
  "QI",
  "QJ",
  "QK",
  "QL",
  "QM",
  "QN",
  "QO",
  "QQ",
  "QR",
  "QS",
  "QT",
  "QU",
  "QV",
  "QW",
  "QX",
  "QY",
  "QZ",
  "R0",
  "R1",
  "R2",
  "R3",
  "R4",
  "R5",
  "R6",
  "R7",
  "R8",
  "R9",
  "RA",
  "RB",
  "RC",
  "RD",
  "RE",
  "RF",
  "RG",
  "RH",
  "RI",
  "RJ",
  "RK",
  "RL",
  "RO",
  "RP",
  "RQ",
  "RR",
  "RS",
  "RU",
  "RV",
  "RW",
  "RX",
  "RZ",
  "S0",
  "S2",
  "S3",
  "S4",
  "S5",
  "S6",
  "S7",
  "S8",
  "S9",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SF",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SP",
  "SQ",
  "SR",
  "SS",
  "ST",
  "SU",
  "SV",
  "SW",
  "SX",
  "SY",
  "T2",
  "T3",
  "T4",
  "T5",
  "T6",
  "T7",
  "T9",
  "TA",
  "TB",
  "TC",
  "TD",
  "TE",
  "TF",
  "TG",
  "TH",
  "TI",
  "TK",
  "TL",
  "TN",
  "TO",
  "TP",
  "TQ",
  "TR",
  "TS",
  "TT",
  "TU",
  "TV",
  "TW",
  "TX",
  "TY",
  "TZ",
  "U2",
  "U3",
  "U4",
  "U5",
  "U6",
  "U7",
  "U8",
  "U9",
  "UA",
  "UB",
  "UD",
  "UE",
  "UF",
  "UG",
  "UH",
  "UI",
  "UK",
  "UL",
  "UM",
  "UN",
  "UO",
  "UP",
  "UQ",
  "US",
  "UT",
  "UU",
  "UX",
  "UY",
  "UZ",
  "V0",
  "V2",
  "V3",
  "V4",
  "V5",
  "V7",
  "V8",
  "V9",
  "VA",
  "VC",
  "VD",
  "VE",
  "VF",
  "VG",
  "VI",
  "VJ",
  "VK",
  "VL",
  "VM",
  "VN",
  "VO",
  "VP",
  "VR",
  "VS",
  "VT",
  "VU",
  "VV",
  "VW",
  "VX",
  "VY",
  "VZ",
  "W2",
  "W3",
  "W4",
  "W5",
  "W6",
  "W8",
  "W9",
  "WA",
  "WB",
  "WC",
  "WD",
  "WE",
  "WF",
  "WG",
  "WH",
  "WJ",
  "WK",
  "WN",
  "WO",
  "WR",
  "WS",
  "WV",
  "WW",
  "WX",
  "WY",
  "X3",
  "X7",
  "XE",
  "XF",
  "XG",
  "XJ",
  "XK",
  "XL",
  "XM",
  "XO",
  "XP",
  "XQ",
  "XS",
  "XT",
  "XW",
  "XY",
  "Y0",
  "Y4",
  "Y5",
  "Y8",
  "Y9",
  "YK",
  "YL",
  "YM",
  "YS",
  "YT",
  "YV",
  "YW",
  "YX",
  "Z3",
  "Z4",
  "Z7",
  "Z8",
  "ZA",
  "ZB",
  "ZE",
  "ZG",
  "ZH",
  "ZI",
  "ZK",
  "ZL",
  "ZP",
  "ZS",
  "ZT",
  "ZU",
  "ZV",
  "ZW",
  "ZX",
  "ZY",
] as const;

export type AirLineIATACode = (typeof AirLineIATACode)[number];

export const airLineNameMap: Record<AirLineIATACode, string> = {
  "20": "Air Salone",
  "04": "Antrak Air",
  "0A": "Amber Air",
  "0B": "Blue Air",
  "0D": "Darwin Airline",
  "0J": "Jetclub",
  "1A": "Amadeus Global Travel Distribution",
  "1B": "Abacus International",
  "1C": "Electronic Data Systems",
  "1D": "Radixx Solutions International",
  "1E": "Travelsky Technology",
  "1F": "INFINI Travel Information",
  "1G": "Galileo International",
  "1H": "Siren-Travel",
  "1I": "Deutsche Rettungsflugwacht",
  "1K": "Southern Cross Distribution",
  "1L": "Open Skies Consultative Commission",
  "1M": "JSC Transport Automated Information Systems",
  "1N": "Navitaire",
  "1P": "Worldspan",
  "1Q": "Sirena",
  "1R": "Hainan Phoenix Information Systems",
  "1S": "Sabre",
  "1T": "1Time Airline",
  "1U": "ITA Software",
  "1W": "Wings Air",
  "1Z": "Sabre Pacific",
  "2A": "Deutsche Bahn",
  "2B": "Aerocondor",
  "2C": "SNCF",
  "2D": "Aero VIP",
  "2F": "Frontier Flying Service",
  "2G": "Cargoitalia",
  "2H": "Thalys",
  "2J": "Air Burkina",
  "2K": "Aerolineas Galapagos (Aerogal)",
  "2L": "Helvetic Airways",
  "2M": "Moldavian Airlines",
  "2N": "Yuzhmashavia",
  "2O": "Air Salone",
  "2P": "Air Philippines",
  "2Q": "Air Cargo Carriers",
  "2R": "VIA Rail Canada",
  "2S": "Island Express",
  "2T": "Haiti Ambassador Airlines",
  "2U": "Air Guinee Express",
  "2V": "Amtrak",
  "2W": "Welcome Air",
  "2Z": "Changan Airlines",
  "3C": "RegionsAir",
  "3G": "Atlant-Soyuz Airlines",
  "3J": "Zip",
  "3K": "Jetstar Asia Airways",
  "3L": "Intersky",
  "3N": "Air Urga",
  "3P": "Tiara Air",
  "3Q": "Yunnan Airlines",
  "3R": "Moskovia Airlines",
  "3S": "Aeroland Airways",
  "3T": "Turan Air",
  "3U": "Sichuan Airlines",
  "3V": "TNT Airways",
  "3W": "Euromanx Airways",
  "4A": "Air Kiribati",
  "4C": "Aires",
  "4D": "Air Sinai",
  "4F": "Air City",
  "4G": "Advance Leasing Company",
  "4K": "Askari Aviation",
  "4M": "Aero 2000",
  "4N": "Air North Charter - Canada",
  "4R": "Hamburg International",
  "4S": "Finalair Congo",
  "4T": "Belair Airlines",
  "4U": "Germanwings",
  "4Y": "Airbus France",
  "5A": "Alpine Air Express",
  "5C": "CAL Cargo Air Lines",
  "5D": "Aerolitoral",
  "5F": "Arctic Circle Air Service",
  "5G": "Skyservice Airlines",
  "5J": "Cebu Pacific",
  "5K": "Hi Fly",
  "5L": "Aerosur",
  "5M": "Sibaviatrans",
  "5N": "Aeroflot-Nord",
  "5T": "Canadian North",
  "5V": "Lviv Airlines",
  "5W": "Astraeus",
  "5X": "United Parcel Service",
  "5Y": "Atlas Air",
  "5Z": "Bismillah Airlines",
  "6A": "Consorcio Aviaxsa",
  "6B": "TUIfly Nordic",
  "6E": "IndiGo Airlines",
  "6G": "Air Wales",
  "6H": "Israir",
  "6I": "International Business Air",
  "6J": "Skynet Asia Airways",
  "6K": "Asian Spirit",
  "6N": "Nordic Regional",
  "6P": "Club Air",
  "6Q": "Slovak Airlines",
  "6R": "Alrosa Mirny Air Enterprise",
  "6T": "Air Mandalay",
  "6U": "Air Ukraine",
  "6V": "Air Vegas",
  "6W": "Saratov Aviation Division",
  "6Z": "Ukrainian Cargo Airways",
  "7A": "Aztec Worldwide Airlines",
  "7B": "Krasnojarsky Airlines",
  "7C": "Coyne Aviation",
  "7E": "Aeroline GmbH",
  "7F": "First Air",
  "7G": "Star Flyer",
  "7K": "Kogalymavia Air Company",
  "7L": "Sun D'Or",
  "7N": "Centavia",
  "7O": "Galaxy Air",
  "7P": "Metro Batavia",
  "7R": "BRA-Transportes Aereos",
  "7T": "Air Glaciers",
  "7W": "Wayraperú",
  "8A": "Atlas Blue",
  "8B": "Caribbean Star Airlines",
  "8C": "Air Horizon",
  "8D": "Astair",
  "8E": "Bering Air",
  "8F": "Fischer Air",
  "8H": "Heli France",
  "8I": "Myway Airlines",
  "8J": "Komiinteravia",
  "8L": "Cargo Plus Aviation",
  "8M": "Maxair",
  "8N": "Barents AirLink",
  "8O": "West Coast Air",
  "8P": "Pacific Coastal Airline",
  "8Q": "Baker Aviation",
  "8R": "TRIP Linhas Aéreas",
  "8S": "Scorpio Aviation",
  "8T": "Air Tindi",
  "8U": "Afriqiyah Airways",
  "8V": "Astral Aviation",
  "8W": "BAX Global",
  "8Y": "Air Burundi",
  "8z": "Linea Aerea de Servicio Ejecutivo Regional",
  "9E": "Pinnacle Airlines",
  "9I": "Thai Sky Airlines",
  "9K": "Cape Air",
  "9L": "Colgan Air",
  "9O": "National Airways Cameroon",
  "9Q": "PB Air",
  "9R": "Phuket Air",
  "9S": "Spring Airlines",
  "9T": "Transwest Air",
  "9U": "Air Moldova",
  "9W": "Jet Airways",
  "9X": "Itali Airlines",
  "9Y": "Air Kazakhstan",
  A2: "Cielos Airlines",
  A3: "Aegean Airlines",
  A4: "Southern Winds Airlines",
  A5: "Airlinair",
  A6: "Air Alps Aviation",
  A7: "Air Plus Comet",
  A8: "Benin Golf Air",
  A9: "Georgian Airways",
  AA: "American Airlines",
  AB: "Air Berlin",
  AC: "Air Canada",
  AD: "Air Paradise International",
  AE: "Mandarin Airlines",
  AF: "Air France",
  AG: "Air Contractors",
  AH: "Air Algérie",
  AI: "Air India Limited",
  AJ: "Aero Contractors",
  AK: "AirAsia",
  AL: "Skywalk Airlines",
  AM: "Aeroméxico",
  AN: "Ansett Australia",
  AO: "Australian Airlines",
  AP: "Air One",
  AQ: "Aloha Airlines",
  AR: "Aerolineas Argentinas",
  AS: "Alaska Airlines",
  AT: "Royal Air Maroc",
  AU: "Austral Lineas Aereas",
  AV: "Avianca - Aerovias Nacionales de Colombia",
  AW: "CHC Airways",
  AX: "Trans States Airlines",
  AY: "Finnair",
  AZ: "Alitalia",
  B2: "Belavia Belarusian Airlines",
  B3: "Bellview Airlines",
  B4: "BACH Flugbetriebsges",
  B5: "Flightline",
  B6: "JetBlue Airways",
  B8: "Eritrean Airlines",
  B9: "Air Bangladesh",
  BA: "British Airways",
  BB: "Seaborne Airlines",
  BC: "Skymark Airlines",
  BD: "bmi",
  BE: "Flybe",
  BF: "Aero-Service",
  BG: "Biman Bangladesh Airlines",
  BH: "Hawkair",
  BI: "Royal Brunei Airlines",
  BJ: "Nouvel Air Tunisie",
  BK: "Potomac Air",
  BL: "Pacific Airlines",
  BM: "Air Sicilia",
  BN: "Braniff International Airways",
  BO: "Bouraq Indonesia Airlines",
  BP: "Air Botswana",
  BQ: "Aeromar",
  BR: "EVA Air",
  BS: "British International Helicopters",
  BT: "Air Baltic",
  BU: "Braathens",
  BV: "Blue Panorama Airlines",
  BW: "Caribbean Airlines",
  BX: "Coast Air",
  BY: "Thomsonfly",
  BZ: "Blue Dart Aviation",
  C0: "Centralwings",
  C3: "ICAR Airlines",
  C4: "Zimex Aviation",
  C5: "CommutAir",
  C6: "CanJet",
  C7: "Rico Linhas Aéreas",
  C8: "Chicago Express",
  C9: "Cirrus Airlines",
  CA: "Air China",
  CC: "Air Atlanta Icelandic",
  CD: "Alliance Air",
  CE: "Nationwide Airlines",
  CF: "City Airline",
  CG: "Airlines PNG",
  CH: "Bemidji Airlines",
  CI: "China Airlines",
  CJ: "China Northern Airlines",
  CK: "China Cargo Airlines",
  CL: "Lufthansa CityLine",
  CM: "Copa Airlines",
  CN: "Islands Nationair",
  CO: "Continental Airlines",
  CP: "Canadian Airlines",
  CQ: "Sunshine Express Airlines",
  CR: "OAG",
  CS: "Continental Micronesia",
  CT: "Civil Air Transport",
  CU: "Cubana de Aviación",
  CV: "Air Chathams",
  CW: "Air Marshall Islands",
  CX: "Cathay Pacific",
  CY: "Cyprus Airways",
  CZ: "China Southern Airlines",
  D3: "Daallo Airlines",
  D4: "Alidaunia",
  D5: "Dauair",
  D6: "Interair South Africa",
  D7: "Dinar",
  D8: "Djibouti Airlines",
  D9: "Aeroflot-Don",
  DA: "Air Georgia",
  DB: "Brit Air",
  DC: "Golden Air",
  DD: "Nok Air",
  DE: "Condor Flugdienst",
  DG: "South East Asian Airlines",
  DH: "Discovery Airways",
  DI: "dba",
  DJ: "Pacific Blue",
  DK: "Eastland Air",
  DL: "Delta Air Lines",
  DM: "Maersk",
  DO: "Dominicana de Aviación",
  DP: "First Choice Airways",
  DQ: "Coastal Air",
  DR: "Air Mediterranee",
  DT: "TAAG Angola Airlines",
  DU: "Hemus Air",
  DV: "Lufttaxi Fluggesellschaft",
  DW: "Aero-Charter Ukraine",
  DX: "DAT Danish Air Transport",
  DY: "Norwegian Air Shuttle",
  E0: "Eos Airlines",
  E2: "Kampuchea Airlines",
  E3: "Domodedovo Airlines",
  E4: "Aero Asia International",
  E5: "Samara Airlines",
  E6: "Bringer Air Cargo Taxi Aereo",
  E7: "Estafeta Carga Aerea",
  E8: "Alpi Eagles",
  E9: "Boston-Maine Airways",
  EA: "European Air Express",
  EC: "Avialeasing Aviation Company",
  ED: "Airblue",
  EE: "Aero Airlines",
  EF: "Far Eastern Air Transport",
  EG: "Japan Asia Airways",
  EH: "Air Nippon Network Co. Ltd.",
  EI: "Aer Lingus",
  EJ: "New England Airlines",
  EK: "Emirates Airline",
  EL: "Air Nippon",
  EM: "Aero Benin",
  EN: "Air Dolomiti",
  EO: "Express One International",
  EP: "Iran Aseman Airlines",
  EQ: "TAME",
  ER: "Astar Air Cargo",
  ES: "DHL International",
  ET: "Ethiopian Airlines",
  EU: "Empresa Ecuatoriana De Aviacion",
  EV: "Atlantic Southeast Airlines",
  EW: "Eurowings",
  EX: "Air Santo Domingo",
  EY: "Etihad Airways",
  EZ: "Evergreen International Airlines",
  F2: "Fly Air",
  F3: "Faso Airways",
  F4: "Albarka Air",
  F5: "Cosmic Air",
  F6: "Faroejet",
  F7: "Flybaboo",
  F9: "Frontier Airlines",
  FA: "Safair",
  FB: "Bulgaria Air",
  FC: "Finncomm Airlines",
  FD: "Thai AirAsia",
  FE: "Primaris Airlines",
  FF: "Airshop",
  FG: "Ariana Afghan Airlines",
  FH: "Futura International Airways",
  FI: "Icelandair",
  FJ: "Air Pacific",
  FK: "Africa West",
  FL: "AirTran Airways",
  FM: "Shanghai Airlines",
  FN: "Regional Airlines",
  FO: "Airlines Of Tasmania",
  FP: "Freedom Air",
  FQ: "Thomas Cook Airlines",
  FR: "Ryanair",
  FS: "Servicios de Transportes Aéreos Fueguinos",
  FT: "Siem Reap Airways",
  FV: "Pulkovo Aviation Enterprise",
  FW: "Ibex Airlines",
  FX: "Federal Express",
  FY: "Firefly",
  G0: "Ghana International Airlines",
  G1: "Gorkha Airlines",
  G2: "Avirex",
  G3: "City Connexion Airlines",
  G4: "Allegiant Air",
  G6: "Guine Bissaur Airlines",
  G7: "Gandalf Airlines",
  G8: "Air Service Gabon",
  G9: "Air Arabia",
  GA: "Garuda Indonesia",
  GB: "ABX Air",
  GC: "Gambia International Airlines",
  GD: "Air Alpha Greenland",
  GE: "TransAsia Airways",
  GF: "Gulf Air Bahrain",
  GG: "Air Comores International",
  GH: "Ghana Airways",
  GI: "Itek Air",
  GJ: "Compania Mexicargo",
  GK: "Go One Airways",
  GL: "Air Greenland",
  GM: "Air Slovakia",
  GN: "Air Gabon",
  GO: "Kuzu Airlines Cargo",
  GP: "Gestair",
  GQ: "Big Sky Airlines",
  GR: "Aurigny Air Services",
  GS: "Air Foyle",
  GT: "GB Airways",
  GV: "Aero Flight",
  GW: "Kuban Airlines",
  GX: "Jetx Airlines",
  GY: "Guyana Airways 2000",
  GZ: "Rotation International Air Services",
  H2: "Sky Airline",
  H4: "HÃ©li SÃ©curitÃ© Helicopter Airlines",
  H5: "Hola Airlines",
  H6: "Hageland Aviation Services",
  H7: "Eagle Air",
  H8: "Dalavia",
  H9: "Air D'Ayiti",
  HA: "Hawaiian Airlines",
  HB: "Harbor Airlines",
  HC: "Aero-Tropics Air Services",
  HD: "Hokkaido International Airlines",
  HE: "Luftfahrtgesellschaft Walter",
  HF: "Hapagfly",
  HG: "Niki",
  HH: "Hope Air",
  HJ: "Asian Express Airlines",
  HK: "Four Star Aviation / Four Star Cargo",
  HM: "Air Seychelles",
  HN: "Heavylift Cargo Airlines",
  HO: "Antinea Airlines",
  HP: "America West Airlines",
  HQ: "Harmony Airways",
  HR: "China United Airlines",
  HT: "Aeromist-Kharkiv",
  HU: "Hainan Airlines",
  HV: "Transavia Holland",
  HW: "Hello",
  HY: "Uzbekistan Airways",
  HZ: "Sat Airlines",
  I4: "Interstate Airline",
  I6: "Sky Eyes",
  I7: "Paramount Airways",
  I9: "Air Italy",
  IA: "Iraqi Airways",
  IB: "Iberia Airlines",
  IC: "Indian Airlines",
  ID: "Interlink Airlines",
  IE: "Solomon Airlines",
  IF: "Islas Airways",
  IG: "Meridiana",
  IH: "Falcon Aviation",
  II: "IBC Airways",
  IJ: "Great Wall Airlines",
  IK: "Imair Airlines",
  IM: "Menajet",
  IN: "MAT Macedonian Airlines",
  IO: "Indonesian Airlines",
  IP: "Atyrau Air Ways",
  IQ: "Augsburg Airways",
  IR: "Iran Air",
  IS: "Island Airlines",
  IT: "Kingfisher Airlines",
  IV: "Wind Jet",
  IW: "AOM French Airlines",
  IX: "Air India Express",
  IY: "Yemenia",
  IZ: "Arkia Israel Airlines",
  J2: "Azerbaijan Airlines",
  J3: "Northwestern Air",
  J4: "Buffalo Airways",
  J6: "AVCOM",
  J7: "Centre-Avia",
  J8: "Berjaya Air",
  J9: "Guinee Airlines",
  JA: "Air Bosna",
  JB: "Helijet",
  JC: "JAL Express",
  JE: "Mango",
  JF: "Jetairfly",
  JH: "Nordeste Linhas Aereas Regionais",
  JI: "Midway Airlines",
  JJ: "TAM Brazilian Airlines",
  JK: "Spanair",
  JL: "Japan Airlines Domestic",
  JM: "Air Jamaica",
  JN: "Excel Airways",
  JO: "JALways",
  JP: "Adria Airways",
  JQ: "Jetstar Airways",
  JR: "Aero California",
  JS: "Air Koryo",
  JT: "Lion Mentari Airlines",
  JU: "Jat Airways",
  JV: "Bearskin Lake Air Service",
  JW: "Arrow Air",
  JX: "Jett8 Airlines Cargo",
  JY: "Air Turks and Caicos",
  JZ: "Skyways Express",
  K2: "Eurolot",
  K4: "Kalitta Air",
  K5: "Aban Air",
  K6: "Bravo Air Congo",
  K8: "Airlink Zambia",
  K9: "Krylo Airlines",
  KA: "Dragonair",
  KB: "Druk Air",
  KC: "Air Astana",
  KD: "KD Avia",
  KE: "Korean Air",
  KF: "Blue1",
  KG: "LAI - Linea Aerea IAACA",
  KI: "Adam Air",
  KJ: "British Mediterranean Airways",
  KK: "Atlasjet",
  KL: "KLM Royal Dutch Airlines",
  KM: "Air Malta",
  KO: "Alaska Central Express",
  KP: "Kiwi International Air Lines",
  KQ: "Kenya Airways",
  KR: "Comores Airlines",
  KS: "Peninsula Airways",
  KU: "Kuwait Airways",
  KV: "Kavminvodyavia",
  KX: "Cayman Airways",
  KY: "Air São Tomé and Príncipe",
  KZ: "Nippon Cargo Airlines",
  L1: "Lufthansa Systems",
  L2: "Lynden Air Cargo",
  L3: "DHL de Guatemala",
  L5: "Lufttransport",
  L6: "Tbilaviamsheni",
  L7: "Laoag International Airlines",
  L8: "Air Luxor GB",
  L9: "Teamline Air",
  LA: "LAN Airlines",
  LB: "Lloyd Aereo Boliviano",
  LC: "Varig Logística",
  LD: "Air Hong Kong",
  LF: "FlyNordic",
  LG: "Luxair",
  LH: "Lufthansa Cargo",
  LI: "Leeward Islands Air Transport",
  LJ: "Sierra National Airlines",
  LK: "Air Luxor",
  LL: "Allegro",
  LM: "Linhas Aéreas de Moçambique",
  LN: "Libyan Arab Airlines",
  LO: "LOT Polish Airlines",
  LP: "LAN Peru",
  LQ: "Lebanese Air Transport",
  LR: "LACSA",
  LS: "Jet2.com",
  LT: "LTU International",
  LU: "LAN Express",
  LV: "Albanian Airlines",
  LW: "Pacific Wings",
  LX: "Swiss International Air Lines",
  LY: "El Al Israel Airlines",
  LZ: "Balkan Bulgarian Airlines",
  M2: "Mahfooz Aviation",
  M3: "ABSA - Aerolinhas Brasileiras",
  M4: "Nova Airline",
  M5: "Kenmore Air",
  M6: "Amerijet International",
  M7: "Marsland Aviation",
  M9: "Motor Sich",
  MA: "Malév Hungarian Airlines",
  MB: "Execair Aviation",
  MC: "Air Mobility Command",
  MD: "Air Madagascar",
  ME: "Middle East Airlines",
  MF: "Xiamen Airlines",
  MG: "Champion Air",
  MH: "Malaysia Airlines",
  MI: "SilkAir",
  MJ: "Líneas Aéreas Privadas Argentinas",
  MK: "Air Mauritius",
  ML: "African Transport Trading and Investment Company",
  MM: "EuroAtlantic Airways",
  MN: "Comair",
  MO: "Abu Dhabi Amiri Flight",
  MP: "Martinair",
  MQ: "American Eagle Airlines",
  MR: "Air Mauritanie",
  MS: "Egyptair",
  MT: "Thomas Cook Airlines",
  MU: "China Eastern Airlines",
  MV: "Armenian International Airways",
  MW: "Maya Island Air",
  MX: "Mexicana de Aviación",
  MY: "Maxjet Airways",
  MZ: "Merpati Nusantara Airlines",
  N2: "Dagestan Airlines",
  N3: "Omskavia Airline",
  N4: "Mountain Air Company",
  N5: "Kyrgyz Airlines",
  N6: "Lagun Air",
  N7: "National Airlines",
  N8: "Fika Salaama Airlines",
  N9: "North Coast Aviation",
  NA: "National Airlines",
  NB: "Sterling Airlines",
  NC: "National Jet Systems",
  NE: "SkyEurope",
  NF: "Air Vanuatu",
  NG: "Lauda Air",
  NH: "All Nippon Airways",
  NI: "Portugalia",
  NK: "Spirit Airlines",
  NL: "Shaheen Air International",
  NM: "Air Madrid",
  NN: "VIM Airlines",
  NO: "Aus-Air",
  NQ: "Air Japan",
  NR: "Pamir Airways",
  NT: "Binter Canarias",
  NU: "Japan Transocean Air",
  NV: "Air Central",
  NW: "Northwest Airlines",
  NX: "Air Macau",
  NY: "Air Iceland",
  NZ: "Air New Zealand",
  O2: "Oceanic Airlines",
  O6: "Oceanair",
  O7: "Ozjet Airlines",
  O8: "Oasis Hong Kong Airlines",
  OA: "Olympic Airlines",
  OB: "Astrakhan Airlines",
  OE: "Asia Overnight Express",
  OF: "Air Finland",
  OH: "Comair",
  OJ: "Overland Airways",
  OK: "Czech Airlines",
  OL: "Ostfriesische Lufttransport",
  OM: "MIAT Mongolian Airlines",
  ON: "Nauru Air Corporation",
  OO: "SkyWest",
  OP: "Chalk's Ocean Airways",
  OR: "Arkefly",
  OS: "Austrian Airlines",
  OT: "Aeropelican Air Services",
  OU: "Croatia Airlines",
  OV: "Estonian Air",
  OW: "Executive Airlines",
  OX: "Orient Thai Airlines",
  OY: "Omni Air International",
  OZ: "Asiana Airlines",
  P0: "Proflight Commuter Services",
  P5: "AeroRepública",
  P7: "Russian Sky Airlines",
  P8: "Pantanal Linhas AÃ©reas",
  P9: "Nas Air",
  PA: "Florida Coastal Airlines",
  PC: "Air Fiji",
  PD: "Porter Airlines",
  PE: "Air Europe",
  PF: "Palestinian Airlines",
  PG: "Bangkok Airways",
  PH: "Polynesian Airlines",
  PI: "Piedmont Airlines (1948-1989)",
  PJ: "Air Saint Pierre",
  PK: "Pakistan International Airlines",
  PL: "Aeroperú",
  PM: "Tropic Air",
  PN: "Pan American Airways",
  PO: "Polar Air Cargo",
  PQ: "Panafrican Airways",
  PR: "Philippine Airlines",
  PS: "Pacific Southwest Airlines",
  PT: "Capital Cargo International Airlines",
  PU: "PLUNA",
  PV: "PAN Air",
  PW: "Precision Air",
  PX: "Air Niugini",
  PY: "Surinam Airways",
  PZ: "TAM Mercosur",
  Q3: "Zambian Airways",
  Q4: "Mastertop Linhas Aereas",
  Q5: "40-Mile Air",
  Q6: "Aero Condor Peru",
  Q8: "Pacific East Asia Cargo Airlines",
  Q9: "Afrinat International Airlines",
  QB: "Georgian National Airlines",
  QC: "Air Corridor",
  QD: "Air Class Lineas Aereas",
  QE: "Crossair Europe",
  QF: "Qantas",
  QH: "Air Florida",
  QI: "Cimber Air",
  QJ: "Jet Airways",
  QK: "Air Canada Jazz",
  QL: "Aero Lanka",
  QM: "Air Malawi",
  QN: "Air Armenia",
  QO: "Aeromexpress",
  QQ: "Alliance Airlines",
  QR: "Qatar Airways",
  QS: "African Safari Airways",
  QT: "TAMPA",
  QU: "East African",
  QV: "Lao Airlines",
  QW: "Blue Wings",
  QX: "Horizon Air",
  QY: "European Air Transport",
  QZ: "Indonesia AirAsia",
  R0: "Royal Airlines",
  R1: "Sirin",
  R2: "Orenburg Airlines",
  R3: "Aircompany Yakutia",
  R4: "Rossiya",
  R5: "Jordan Aviation",
  R6: "RACSA",
  R7: "Aserca Airlines",
  R8: "Kyrgyzstan Airlines",
  R9: "Camai Air",
  RA: "Nepal Airlines",
  RB: "Air Srpska",
  RC: "Atlantic Airways",
  RD: "Ryan International Airlines",
  RE: "Aer Arann",
  RF: "Florida West International Airways",
  RG: "VRG Linhas Aereas",
  RH: "Republic Express Airlines",
  RI: "Mandala Airlines",
  RJ: "Royal Jordanian",
  RK: "Air Afrique",
  RL: "Royal Phnom Penh Airways",
  RO: "Tarom",
  RP: "Chautauqua Airlines",
  RQ: "Kam Air",
  RR: "Royal Air Force",
  RS: "Intercontinental de Aviación",
  RU: "AirBridge Cargo",
  RV: "Caspian Airlines",
  RW: "Republic Airlines",
  RX: "Aviaexpress",
  RZ: "Euro Exec Express",
  S0: "Slok Air Gambia",
  S2: "Air Sahara",
  S3: "Santa Barbara Airlines",
  S4: "SATA International",
  S5: "Shuttle America",
  S6: "Star Air",
  S7: "S7 Airlines",
  S8: "Chari Aviation Services",
  S9: "East African Safari Air",
  SA: "South African Airways",
  SB: "Air Caledonie International",
  SC: "Shandong Airlines",
  SD: "Sudan Airways",
  SE: "XL Airways France",
  SF: "Tassili Airlines",
  SG: "JetsGo",
  SH: "Fly Me Sweden",
  SI: "Skynet Airlines",
  SJ: "Freedom Air",
  SK: "Scandinavian Airlines System",
  SL: "Rio Sul Serviços Aéreos Regionais",
  SM: "Swedline Express",
  SN: "Brussels Airlines",
  SO: "Sosoliso Airlines",
  SP: "SATA Air Acores",
  SQ: "Singapore Airlines Cargo",
  SR: "Swissair",
  SS: "Corsairfly",
  ST: "Germania",
  SU: "Aeroflot Russian Airlines",
  SV: "Saudi Arabian Airlines",
  SW: "Air Namibia",
  SX: "Skybus Airlines",
  SY: "Sun Country Airlines",
  T2: "Thai Air Cargo",
  T3: "Eastern Airways",
  T4: "Hellas Jet",
  T5: "Turkmenistan Airlines",
  T6: "Tavrey Airlines",
  T7: "Twin Jet",
  T9: "Thai Star Airlines",
  TA: "Grupo TACA",
  TB: "TUI Airlines Belgium",
  TC: "Air Tanzania",
  TD: "Atlantis European Airways",
  TE: "FlyLal",
  TF: "MalmÃ¶ Aviation",
  TG: "Thai Airways International",
  TH: "BA Connect",
  TI: "Tol-Air Services",
  TK: "Turkish Airlines",
  TL: "Airnorth",
  TN: "Air Tahiti Nui",
  TO: "President Airlines",
  TP: "TAP Portugal",
  TQ: "Tandem Aero",
  TR: "Tiger Airways",
  TS: "Air Transat",
  TT: "Air Lithuania",
  TU: "Tunisair",
  TV: "Virgin Express",
  TW: "Trans World Airlines",
  TX: "Air Caraïbes",
  TY: "Air Calédonie",
  TZ: "ATA Airlines",
  U2: "United Feeder Service",
  U3: "Avies",
  U4: "PMTair",
  U5: "USA3000 Airlines",
  U6: "Ural Airlines",
  U7: "Northern Dene Airways",
  U8: "Armavia",
  U9: "Tatarstan Airlines",
  UA: "United Airlines",
  UB: "Myanma Airways",
  UD: "Hex'Air",
  UE: "Nasair",
  UF: "UM Airlines",
  UG: "Tuninter",
  UH: "US Helicopter Corporation",
  UI: "Eurocypria Airlines",
  UK: "buzz",
  UL: "SriLankan Airlines",
  UM: "Air Zimbabwe",
  UN: "Transaero Airlines",
  UO: "Hong Kong Express Airways",
  UP: "Bahamasair",
  UQ: "O'Connor Airlines",
  US: "US Airways",
  UT: "UTair Aviation",
  UU: "Air Austral",
  UX: "Air Europa",
  UY: "Cameroon Airlines",
  UZ: "El-Buraq Air Transport",
  V0: "Conviasa",
  V2: "Karat",
  V3: "Carpatair",
  V4: "Reem Air",
  V5: "Avolar Aerolineas",
  V7: "Air Senegal International",
  V8: "ATRAN Cargo Airlines",
  V9: "BAL Bashkirian Airlines",
  VA: "V Australia Airlines",
  VC: "Ocean Airlines",
  VD: "Air Liberté",
  VE: "Avensa",
  VF: "Valuair",
  VG: "VLM Airlines",
  VI: "Volga-Dnepr Airlines",
  VJ: "Jatayu Airlines",
  VK: "Virgin Nigeria Airways",
  VL: "Air VIA",
  VM: "Viaggio Air",
  VN: "Vietnam Airlines",
  VO: "Austrian Arrows",
  VP: "VASP",
  VR: "TACV",
  VS: "Virgin Atlantic Airways",
  VT: "Air Tahiti",
  VU: "Air Ivoire",
  VV: "Aerosvit Airlines",
  VW: "Aeromar",
  VX: "ACES Colombia",
  VY: "Formosa Airlines",
  VZ: "MyTravel Airways",
  W2: "Canadian Western Airlines",
  W3: "Flyhy Cargo Airlines",
  W4: "Aero Services Executive",
  W5: "Mahan Air",
  W6: "Wizz Air",
  W8: "Cargojet Airways",
  W9: "Abelag Aviation",
  WA: "KLM Cityhopper",
  WB: "Rwandair Express",
  WC: "Islena De Inversiones",
  WD: "DAS Air Cargo",
  WE: "Centurion Air Cargo",
  WF: "Widerøe",
  WG: "Sunwing Airlines",
  WH: "China Northwest Airlines",
  WJ: "WebJet Linhas Aéreas",
  WK: "American Falcon",
  WN: "Southwest Airlines",
  WO: "World Airways",
  WR: "Royal Tongan Airlines",
  WS: "WestJet",
  WV: "Swe Fly",
  WW: "bmibaby",
  WX: "CityJet",
  WY: "Oman Air",
  X3: "Hapag-Lloyd Express (TUIfly)",
  X7: "Chitaavia",
  XE: "ExpressJet",
  XF: "Vladivostok Air",
  XG: "Calima Aviacion",
  XJ: "Mesaba Airlines",
  XK: "Corse-Mediterranee",
  XL: "Aerolane",
  XM: "J-Air",
  XO: "China Xinhua Airlines",
  XP: "Xtra Airways",
  XQ: "SunExpress",
  XS: "SITA",
  XT: "Air Exel",
  XW: "Sky Express",
  XY: "Nas Air",
  Y0: "Yellow Air Taxi",
  Y4: "Volaris",
  Y5: "Pace Airlines",
  Y8: "Yangtze River Express",
  Y9: "Kish Air",
  YK: "Cyprus Turkish Airlines",
  YL: "Yamal Airlines",
  YM: "Montenegro Airlines",
  YS: "Régional",
  YT: "Air Togo",
  YV: "Mesa Airlines",
  YW: "Air Nostrum",
  YX: "Midwest Airlines",
  Z3: "Avient Aviation",
  Z4: "Zoom Airlines",
  Z7: "ADC Airlines",
  Z8: "Amaszonas",
  ZA: "Access Air",
  ZB: "Air Bourbon",
  ZE: "Arcus-Air Logistic",
  ZG: "Viva Macau",
  ZH: "Shenzhen Airlines",
  ZI: "Aigle Azur",
  ZK: "Great Lakes Airlines",
  ZL: "Regional Express",
  ZP: "Silk Way Airlines",
  ZS: "Azzurra Air",
  ZT: "Titan Airways",
  ZU: "Helios Airways",
  ZV: "Air Midwest",
  ZW: "Air Wisconsin",
  ZX: "Air Georgian",
  ZY: "Ada Air",
} as const;
