export const AirportIATACode = [
  "AAR",
  "ABD",
  "AEH",
  "ABZ",
  "ABR",
  "ABJ",
  "ABI",
  "AUH",
  "ABV",
  "AUE",
  "ABS",
  "ACA",
  "ACC",
  "ADA",
  "ADD",
  "ADL",
  "ADE",
  "ADF",
  "AER",
  "AJY",
  "AGA",
  "SUM",
  "AGZ",
  "BQN",
  "AGU",
  "AMD",
  "AYU",
  "AJA",
  "AXT",
  "CAK",
  "AKT",
  "AAN",
  "AAC",
  "ALH",
  "ABY",
  "ALB",
  "LBI",
  "AAL",
  "ABQ",
  "ABX",
  "ACI",
  "ALP",
  "AES",
  "ALJ",
  "HBH",
  "ALY",
  "ESF",
  "FJR",
  "AHO",
  "ALG",
  "AHU",
  "ALC",
  "ASP",
  "ADY",
  "ABE",
  "ALA",
  "LEI",
  "ALF",
  "AAT",
  "ACH",
  "AOO",
  "AXS",
  "ASJ",
  "AMA",
  "AZB",
  "AMM",
  "ADJ",
  "ATQ",
  "AMS",
  "QNB",
  "ANC",
  "AOI",
  "ALV",
  "AXA",
  "AJN",
  "ANK",
  "ESB",
  "AAE",
  "ARB",
  "NCY",
  "ANB",
  "AYT",
  "TNR",
  "ANU",
  "ANR",
  "AOJ",
  "APW",
  "ATW",
  "AQJ",
  "AJU",
  "ARH",
  "ARK",
  "GPA",
  "RLT",
  "ACE",
  "AUA",
  "AVL",
  "ASB",
  "ASM",
  "ASE",
  "ATZ",
  "TSE",
  "ASU",
  "ASW",
  "ATH",
  "HEW",
  "AHN",
  "ATO",
  "ATL",
  "ACY",
  "YAT",
  "AKL",
  "AGB",
  "AGS",
  "AUG",
  "AUR",
  "AUS",
  "AYW",
  "AYQ",
  "AYR",
  "BJZ",
  "BGW",
  "IXB",
  "NAS",
  "BHV",
  "BAH",
  "BFL",
  "BAK",
  "BNK",
  "BWI",
  "ABM",
  "BKO",
  "BBY",
  "BWN",
  "BDO",
  "BLR",
  "BGU",
  "DMK",
  "BKK",
  "BGR",
  "BGF",
  "BJL",
  "BNP",
  "BCN",
  "BLA",
  "BDU",
  "BRI",
  "BZL",
  "BDQ",
  "BRR",
  "BAQ",
  "BSL",
  "EAP",
  "BSR",
  "PTP",
  "SKB",
  "BIA",
  "BTR",
  "BYU",
  "BPT",
  "BKW",
  "EIS",
  "PEK",
  "NAY",
  "BEW",
  "BEY",
  "BEL",
  "BHD",
  "BFS",
  "IXG",
  "BEG",
  "BZE",
  "BLI",
  "CNF",
  "BJI",
  "BEB",
  "BEN",
  "BUG",
  "BEH",
  "BBT",
  "BGY",
  "BGO",
  "EGC",
  "BER",
  "SXF",
  "TXL",
  "THF",
  "BDA",
  "BRN",
  "ZDJ",
  "BET",
  "BHO",
  "BBI",
  "BIQ",
  "BIO",
  "BIL",
  "BLL",
  "BTU",
  "IRO",
  "BHX",
  "BHM",
  "FRU",
  "BIS",
  "BXO",
  "BLK",
  "BLT",
  "BLZ",
  "BHE",
  "BFN",
  "BMI",
  "BMG",
  "BLF",
  "BVB",
  "BOY",
  "BOO",
  "BJV",
  "BOG",
  "BOI",
  "BLQ",
  "BOM",
  "BON",
  "YVB",
  "BOB",
  "BOD",
  "BXS",
  "BOS",
  "BYK",
  "BOJ",
  "BOH",
  "ZBO",
  "BZN",
  "BFD",
  "BRD",
  "BMP",
  "BSB",
  "BTS",
  "BZV",
  "BRE",
  "VBS",
  "BES",
  "BIV",
  "BDR",
  "BGI",
  "BDS",
  "BNE",
  "BRS",
  "BNN",
  "BHQ",
  "BKX",
  "BME",
  "BQK",
  "BRU",
  "BGA",
  "BUH",
  "OTP",
  "BUD",
  "BUE",
  "EZE",
  "AEP",
  "BFO",
  "BUF",
  "BJM",
  "BUQ",
  "BHC",
  "BDB",
  "BUR",
  "BRL",
  "BTV",
  "BWT",
  "BTM",
  "CAB",
  "CAG",
  "CNS",
  "CAI",
  "CJC",
  "CCU",
  "YYC",
  "CLO",
  "CCJ",
  "CLY",
  "YCB",
  "CBG",
  "CAL",
  "CGR",
  "CBR",
  "CUN",
  "CEQ",
  "CIW",
  "CPT",
  "CCS",
  "CWL",
  "CLD",
  "CVQ",
  "CRF",
  "CSN",
  "CAS",
  "CMN",
  "LRM",
  "CSI",
  "CPR",
  "CST",
  "CTG",
  "SLU",
  "CTA",
  "CAY",
  "CBU",
  "CEB",
  "CDC",
  "CID",
  "CED",
  "CES",
  "KHV",
  "CMF",
  "CMI",
  "IXC",
  "CGQ",
  "CHQ",
  "CHG",
  "CHS",
  "CRW",
  "CLT",
  "CHO",
  "CXT",
  "CHA",
  "CTU",
  "MAA",
  "CYS",
  "CNX",
  "QCB",
  "MDW",
  "ORD",
  "CHI",
  "CZA",
  "CIC",
  "CUU",
  "JKH",
  "CIP",
  "KIV",
  "HTA",
  "CTS",
  "CJL",
  "CGP",
  "CKG",
  "CHC",
  "CCZ",
  "YYQ",
  "CFG",
  "CVG",
  "CME",
  "CGU",
  "CJS",
  "CEN",
  "CVM",
  "CKB",
  "CMQ",
  "CFE",
  "BKL",
  "CLE",
  "CBB",
  "COK",
  "COD",
  "KCC",
  "CFS",
  "CJB",
  "CLQ",
  "CLL",
  "KCE",
  "CGN",
  "CMB",
  "COS",
  "CAE",
  "CSG",
  "CMH",
  "CKY",
  "CCR",
  "CON",
  "CZL",
  "CND",
  "CPD",
  "CTN",
  "OOM",
  "CPH",
  "COR",
  "ODB",
  "CDV",
  "CFU",
  "ORK",
  "CRP",
  "COO",
  "CVT",
  "CZM",
  "CGA",
  "CEC",
  "CGB",
  "CUL",
  "CUR",
  "CWB",
  "CYU",
  "DKR",
  "DLM",
  "DBY",
  "DLC",
  "DAL",
  "DFW",
  "DJO",
  "DAM",
  "DMM",
  "DAN",
  "DAR",
  "DRW",
  "DDI",
  "DAY",
  "DAB",
  "DEC",
  "YDF",
  "DEL",
  "HAG",
  "DNZ",
  "DPS",
  "DEN",
  "DSK",
  "DRB",
  "LDY",
  "DSM",
  "DET",
  "DTW",
  "DTT",
  "DVL",
  "DPO",
  "DHA",
  "DAC",
  "DIL",
  "DLG",
  "DNR",
  "DLP",
  "DJE",
  "JIB",
  "DOD",
  "DOH",
  "DSA",
  "CFN",
  "DTM",
  "DHN",
  "DLA",
  "DRS",
  "DXB",
  "DBO",
  "DUB",
  "DUJ",
  "DBV",
  "DBQ",
  "DUS",
  "DLH",
  "DND",
  "DUD",
  "DKI",
  "DRO",
  "DUR",
  "DYU",
  "DUT",
  "DYA",
  "DZA",
  "ELS",
  "IPC",
  "EAU",
  "EDI",
  "YEA",
  "YEG",
  "YXD",
  "EGS",
  "EIN",
  "AZS",
  "EBA",
  "ETH",
  "VDA",
  "EKI",
  "EKO",
  "ELL",
  "EMY",
  "ELM",
  "ELP",
  "ELY",
  "EDR",
  "EMD",
  "ENF",
  "EBB",
  "ERF",
  "ERI",
  "EVN",
  "ERC",
  "ERZ",
  "EBJ",
  "ESC",
  "EPR",
  "EUG",
  "ACV",
  "EVV",
  "EVE",
  "EXT",
  "FAI",
  "FIE",
  "LYP",
  "FAR",
  "FMN",
  "FAO",
  "FAE",
  "FYV",
  "FAY",
  "FEZ",
  "FSC",
  "FLG",
  "YFO",
  "FNT",
  "FLR",
  "FLO",
  "FLN",
  "FRO",
  "YFA",
  "FOR",
  "FDF",
  "FOD",
  "FHU",
  "FLL",
  "YMM",
  "FMY",
  "RSW",
  "FRI",
  "YSM",
  "FSM",
  "YXJ",
  "VPS",
  "FWA",
  "FOU",
  "FRW",
  "FRA",
  "HHN",
  "FKL",
  "YFC",
  "FPO",
  "FNA",
  "FRJ",
  "FAT",
  "FDH",
  "FUE",
  "FUK",
  "FKS",
  "FNC",
  "FUT",
  "GBE",
  "GAD",
  "GNV",
  "GWY",
  "YQX",
  "GOU",
  "GZA",
  "GZT",
  "GDN",
  "GEX",
  "GVA",
  "GOA",
  "GRJ",
  "GEO",
  "GET",
  "GRO",
  "GNE",
  "GIB",
  "GCC",
  "GIL",
  "YGX",
  "GLT",
  "PIK",
  "GLA",
  "GGW",
  "GDV",
  "GOI",
  "GYN",
  "OOL",
  "GOO",
  "YYR",
  "GOZ",
  "GOT",
  "GOV",
  "GHB",
  "GRX",
  "GCN",
  "GCM",
  "GFK",
  "GJT",
  "GRR",
  "GPZ",
  "GRZ",
  "GTF",
  "GKL",
  "GRB",
  "LWB",
  "GSO",
  "GLH",
  "PGV",
  "GSP",
  "GND",
  "GNB",
  "GFF",
  "GRQ",
  "GTE",
  "GON",
  "GDL",
  "GSI",
  "GUM",
  "CAN",
  "GRU",
  "GUA",
  "GYE",
  "GCI",
  "GTI",
  "GPT",
  "KWL",
  "ULU",
  "GUC",
  "GAU",
  "GWD",
  "GWE",
  "GYP",
  "HAC",
  "HFA",
  "HNS",
  "HKD",
  "YHZ",
  "YUX",
  "HAM",
  "HLT",
  "YHM",
  "HLZ",
  "HTI",
  "HFT",
  "CMX",
  "HGH",
  "HAJ",
  "HAN",
  "HRE",
  "HRB",
  "HRL",
  "YHR",
  "HAR",
  "MDT",
  "BDL",
  "HDY",
  "HAU",
  "HAV",
  "HVR",
  "HIS",
  "HLN",
  "JHE",
  "HEL",
  "HER",
  "HMO",
  "HVB",
  "HIB",
  "HKY",
  "ITO",
  "HHH",
  "HNK",
  "HIJ",
  "SGN",
  "HBA",
  "HOQ",
  "HOG",
  "HMH",
  "HOM",
  "HKG",
  "ZJK",
  "HIR",
  "HNL",
  "HNH",
  "HOR",
  "HOU",
  "IAH",
  "HUH",
  "HUX",
  "HUI",
  "HUY",
  "HTS",
  "HSV",
  "HRG",
  "HON",
  "HWN",
  "HYA",
  "HYG",
  "HYD",
  "HDD",
  "IBZ",
  "IDA",
  "IGR",
  "ILP",
  "IOU",
  "ILI",
  "IPL",
  "IVC",
  "ICN",
  "IND",
  "IGH",
  "IFL",
  "INN",
  "INL",
  "YEV",
  "INV",
  "IYK",
  "YFB",
  "IQT",
  "IKT",
  "ISG",
  "ISB",
  "ILY",
  "IOM",
  "IST",
  "SAW",
  "ITH",
  "IVL",
  "ZIH",
  "IZM",
  "ADB",
  "JAC",
  "JXN",
  "MJQ",
  "JAN",
  "HKS",
  "MKL",
  "LRF",
  "NZC",
  "NIP",
  "JAX",
  "CRG",
  "IJX",
  "OAJ",
  "JKV",
  "JAK",
  "JAG",
  "JCM",
  "JAQ",
  "JAF",
  "JGB",
  "JAI",
  "JSA",
  "HLP",
  "JKT",
  "CGK",
  "JAA",
  "JLR",
  "JAL",
  "JLS",
  "UIT",
  "JMB",
  "DJB",
  "JAM",
  "JMS",
  "JHW",
  "IXJ",
  "JGA",
  "IXW",
  "JKR",
  "JAD",
  "JVL",
  "JNA",
  "JQE",
  "JTI",
  "JAU",
  "DJJ",
  "JED",
  "JEF",
  "JEE",
  "XRY",
  "JER",
  "JRS",
  "JSR",
  "PYB",
  "JGS",
  "JMU",
  "JGN",
  "GJL",
  "JIJ",
  "JIL",
  "JIM",
  "TNA",
  "JDZ",
  "JHG",
  "JNG",
  "JIN",
  "JJN",
  "BCO",
  "JNZ",
  "JIP",
  "JIR",
  "JIU",
  "JIW",
  "JCB",
  "JPA",
  "JDH",
  "JKG",
  "JOE",
  "JNB",
  "BGM",
  "JON",
  "JST",
  "JHB",
  "JOI",
  "JOL",
  "JMO",
  "JBR",
  "JLN",
  "JRH",
  "JOS",
  "JSM",
  "AJF",
  "JJI",
  "JUB",
  "JUI",
  "JDF",
  "JUJ",
  "JCK",
  "JUL",
  "JUM",
  "JUN",
  "JNU",
  "JNI",
  "JUT",
  "JWA",
  "JYV",
  "KBL",
  "KOJ",
  "KCM",
  "OGG",
  "KAJ",
  "KLX",
  "AZO",
  "KGI",
  "KGD",
  "FCA",
  "KLR",
  "YKA",
  "MUE",
  "KAN",
  "KNU",
  "MCI",
  "KHH",
  "JHM",
  "KHI",
  "FKB",
  "KSD",
  "AOK",
  "KTA",
  "KYS",
  "KRB",
  "KRP",
  "ZKE",
  "KSL",
  "KTR",
  "KTM",
  "MPA",
  "KHJ",
  "MKK",
  "KVA",
  "ASR",
  "KZN",
  "KMP",
  "YLW",
  "KEM",
  "ENA",
  "MSE",
  "KIR",
  "KTN",
  "EYW",
  "AHB",
  "UVL",
  "HRK",
  "KRT",
  "KDD",
  "KEL",
  "KBP",
  "IEV",
  "KGL",
  "JRO",
  "ILE",
  "KIM",
  "KNS",
  "AKN",
  "KGC",
  "KIN",
  "ISO",
  "SVD",
  "FIH",
  "CXI",
  "KKN",
  "KIK",
  "KOI",
  "KRN",
  "FKI",
  "KTT",
  "KIW",
  "KLU",
  "LMT",
  "KLW",
  "KLZ",
  "NOC",
  "TYS",
  "UKB",
  "KCZ",
  "ADQ",
  "OHT",
  "KOK",
  "KMQ",
  "KOA",
  "KYA",
  "HGO",
  "KGS",
  "BKI",
  "OTZ",
  "KWM",
  "KRK",
  "KRS",
  "KID",
  "KSU",
  "KUL",
  "SZB",
  "KUA",
  "KCH",
  "KMJ",
  "KNX",
  "KUO",
  "KUH",
  "YVP",
  "YGW",
  "KAO",
  "KWI",
  "UKY",
  "LEK",
  "WLB",
  "LBU",
  "XLB",
  "LCG",
  "LSE",
  "LAE",
  "LRH",
  "LAF",
  "LFT",
  "LOS",
  "YGL",
  "LHE",
  "LCH",
  "HII",
  "TVL",
  "LKL",
  "LBQ",
  "SUF",
  "LMP",
  "LNY",
  "LNS",
  "LEQ",
  "LGK",
  "LAI",
  "HLA",
  "LAN",
  "LPB",
  "LAP",
  "LPP",
  "LAR",
  "LRD",
  "LCA",
  "LPA",
  "LAS",
  "LBE",
  "LST",
  "PIB",
  "LVO",
  "LAW",
  "LZC",
  "YLR",
  "LEA",
  "LEB",
  "LBA",
  "LER",
  "LEJ",
  "LEY",
  "BJX",
  "LNO",
  "LWK",
  "LWS",
  "LWT",
  "LEX",
  "LBV",
  "LDK",
  "LGG",
  "LIF",
  "LIH",
  "LIL",
  "LLW",
  "LIM",
  "QLI",
  "LIG",
  "LNK",
  "LDC",
  "LNZ",
  "LIQ",
  "LIS",
  "LSY",
  "LIT",
  "LPL",
  "LZR",
  "LJU",
  "IRG",
  "LFW",
  "YXU",
  "LON",
  "LCY",
  "LGW",
  "LHR",
  "LTN",
  "STN",
  "LGB",
  "LIJ",
  "ISP",
  "LRE",
  "GGG",
  "LYR",
  "LTO",
  "LRT",
  "LAX",
  "SJD",
  "LMM",
  "TFN",
  "LSZ",
  "LDE",
  "SDF",
  "LAD",
  "LBB",
  "LKO",
  "LUD",
  "MLA",
  "LUG",
  "LLA",
  "FBM",
  "LUN",
  "LUJ",
  "LUX",
  "LUM",
  "LXR",
  "LWO",
  "LYX",
  "LYH",
  "LYS",
  "LYO",
  "MST",
  "MCP",
  "MFM",
  "MCZ",
  "MKY",
  "MCN",
  "NOP",
  "MED",
  "MSN",
  "MAD",
  "SEZ",
  "MAH",
  "MTL",
  "MJN",
  "MZG",
  "SSG",
  "AGP",
  "MLX",
  "MLE",
  "MYD",
  "MMA",
  "MMX",
  "MJC",
  "MGA",
  "MAO",
  "MAN",
  "MHT",
  "MDL",
  "MFO",
  "XMH",
  "MNL",
  "ZLO",
  "MTS",
  "MPM",
  "MDQ",
  "MAR",
  "MFQ",
  "MTH",
  "MQM",
  "MEE",
  "MGH",
  "PMV",
  "MBX",
  "MHQ",
  "MVR",
  "MQT",
  "RAK",
  "RMF",
  "MUH",
  "MRS",
  "MHH",
  "MVY",
  "MRB",
  "MBH",
  "MSU",
  "MCW",
  "MVZ",
  "MMJ",
  "MYJ",
  "MTO",
  "MUB",
  "MAU",
  "MRU",
  "MAZ",
  "MZT",
  "MFE",
  "MES",
  "KNO",
  "MDE",
  "MFR",
  "MKR",
  "MEL",
  "MLB",
  "DOM",
  "MEM",
  "MDZ",
  "MDC",
  "MCE",
  "MID",
  "MEI",
  "MIM",
  "MEZ",
  "MTM",
  "MZM",
  "ETZ",
  "MXL",
  "MEX",
  "AZP",
  "NLU",
  "MFU",
  "MIA",
  "MWD",
  "MMM",
  "MAF",
  "MDY",
  "MIK",
  "MIL",
  "LIN",
  "MXP",
  "MQL",
  "MLS",
  "MFN",
  "MKE",
  "MTT",
  "MRV",
  "MSP",
  "MOT",
  "MSQ",
  "MYY",
  "QML",
  "MSO",
  "MHE",
  "MMY",
  "KMI",
  "MBM",
  "MFF",
  "MOB",
  "MOD",
  "MJD",
  "MGQ",
  "OKU",
  "MLI",
  "MBA",
  "MIR",
  "YQM",
  "MLU",
  "MLW",
  "ROB",
  "MBJ",
  "QGF",
  "MRY",
  "MTY",
  "NTR",
  "MVD",
  "MGM",
  "MPL",
  "YMQ",
  "YUL",
  "YMX",
  "MTJ",
  "MOZ",
  "MOV",
  "MRZ",
  "MLM",
  "MGW",
  "HNA",
  "HAH",
  "MYA",
  "MOW",
  "DME",
  "SVO",
  "VKO",
  "MWH",
  "MZY",
  "OMO",
  "OSM",
  "MJL",
  "MQQ",
  "GTN",
  "MGB",
  "MMG",
  "ISA",
  "MCL",
  "MUC",
  "FMO",
  "MLH",
  "MUX",
  "MJV",
  "MMK",
  "MSR",
  "MCT",
  "MSL",
  "MKG",
  "MFG",
  "MVB",
  "JMK",
  "MYR",
  "CRE",
  "MYQ",
  "MJT",
  "MZF",
  "NAN",
  "NGS",
  "NGO",
  "NAG",
  "NBO",
  "NAJ",
  "NST",
  "ENC",
  "YSR",
  "NNG",
  "NTE",
  "ACK",
  "NAP",
  "APF",
  "NAA",
  "NRA",
  "UAK",
  "BNA",
  "NAT",
  "SUV",
  "WNS",
  "JNX",
  "NDJ",
  "NLA",
  "NSN",
  "NLP",
  "MQP",
  "NEV",
  "EWN",
  "HVN",
  "MSY",
  "NQY",
  "JFK",
  "LGA",
  "EWR",
  "NYC",
  "SWF",
  "BEO",
  "NTL",
  "NCL",
  "NCS",
  "ZNE",
  "PHF",
  "NGE",
  "IAG",
  "NIM",
  "NCE",
  "NIC",
  "NLV",
  "KIJ",
  "FNI",
  "INI",
  "GOJ",
  "OME",
  "NSA",
  "NLK",
  "ORF",
  "YVQ",
  "NRK",
  "OTH",
  "ELH",
  "NWI",
  "EMA",
  "NDB",
  "NKC",
  "NOU",
  "QND",
  "OVB",
  "NUE",
  "NLD",
  "TBU",
  "OAK",
  "OAX",
  "ODE",
  "ODS",
  "ORB",
  "OHD",
  "OIT",
  "OKJ",
  "OKA",
  "OKC",
  "OLB",
  "OLP",
  "OMA",
  "OND",
  "ONT",
  "ORN",
  "OAG",
  "SNA",
  "OMD",
  "ORL",
  "MCO",
  "ORS",
  "OSA",
  "ITM",
  "KIX",
  "OSH",
  "OSI",
  "OSL",
  "FBU",
  "TRF",
  "YOW",
  "ODA",
  "OZZ",
  "OUH",
  "OUA",
  "OUD",
  "OUL",
  "OUK",
  "OVD",
  "OWB",
  "OXR",
  "UVE",
  "PAD",
  "PAH",
  "PGA",
  "PPG",
  "PKB",
  "PMO",
  "PMI",
  "PMW",
  "PMD",
  "PMR",
  "PSP",
  "PTY",
  "PFN",
  "PJG",
  "PNL",
  "PPT",
  "PFO",
  "PBO",
  "PBM",
  "PAR",
  "CDG",
  "LBG",
  "ORY",
  "PBH",
  "PSC",
  "PSI",
  "PAT",
  "PYX",
  "PUF",
  "PLN",
  "PEN",
  "PDT",
  "PNS",
  "PIA",
  "PEI",
  "PGF",
  "PER",
  "PEG",
  "PSR",
  "PEW",
  "PSG",
  "PHW",
  "PHL",
  "PNH",
  "PHX",
  "HKT",
  "PIR",
  "PZB",
  "PTG",
  "NTY",
  "PSA",
  "PIT",
  "PLB",
  "PBZ",
  "PIH",
  "TGD",
  "PNI",
  "PNR",
  "PIS",
  "PSE",
  "PDL",
  "POR",
  "CLM",
  "PAP",
  "PUG",
  "PLZ",
  "POG",
  "PHC",
  "PHE",
  "PTJ",
  "PWM",
  "PDX",
  "PLO",
  "PQQ",
  "YPN",
  "POM",
  "OPO",
  "POA",
  "POS",
  "PSD",
  "PXO",
  "PVH",
  "VLI",
  "POU",
  "POZ",
  "PRG",
  "RAI",
  "PQI",
  "PRY",
  "PVK",
  "YXS",
  "YPR",
  "PRN",
  "PPP",
  "PVD",
  "SCC",
  "PBC",
  "PUB",
  "PXM",
  "PZO",
  "POP",
  "PVR",
  "XPK",
  "PUY",
  "PUW",
  "PNQ",
  "PUQ",
  "PUJ",
  "PUS",
  "FNJ",
  "YQB",
  "UEE",
  "ZQN",
  "UET",
  "TAO",
  "UIP",
  "UIN",
  "UIO",
  "RBA",
  "RYK",
  "RFP",
  "YOP",
  "RAJ",
  "RDU",
  "IXR",
  "RGI",
  "RGN",
  "RAP",
  "RAR",
  "RKT",
  "RAZ",
  "RWP",
  "RDG",
  "REC",
  "RDD",
  "RDM",
  "REG",
  "YQR",
  "TFS",
  "RNS",
  "RNO",
  "YRB",
  "REU",
  "REK",
  "KEF",
  "RHI",
  "RHO",
  "RCB",
  "RIC",
  "RIX",
  "RJK",
  "RMI",
  "RBR",
  "GIG",
  "SDU",
  "RIO",
  "RUH",
  "RNE",
  "ROA",
  "RTB",
  "RST",
  "ROC",
  "RSD",
  "RKS",
  "RFD",
  "ROK",
  "RKD",
  "RWI",
  "RDZ",
  "RRG",
  "RNN",
  "ROM",
  "CIA",
  "FCO",
  "RNB",
  "ROS",
  "RVI",
  "ROV",
  "ROT",
  "RTM",
  "RVN",
  "NDU",
  "ROU",
  "SCN",
  "SMF",
  "SDS",
  "MBS",
  "SDT",
  "SBK",
  "RUN",
  "YSJ",
  "SPN",
  "SID",
  "SLL",
  "SLE",
  "SNS",
  "SNC",
  "SAY",
  "SBY",
  "SKG",
  "SLA",
  "SLC",
  "SSA",
  "SZG",
  "KUF",
  "SKD",
  "SMI",
  "SZF",
  "ADZ",
  "SJT",
  "SAT",
  "BRC",
  "SAN",
  "SFO",
  "SJO",
  "SJC",
  "SJU",
  "SBP",
  "SLP",
  "SPY",
  "SAP",
  "ZSA",
  "SAL",
  "EAS",
  "SAH",
  "YZP",
  "SBA",
  "SPC",
  "SRZ",
  "SKV",
  "SMA",
  "SMX",
  "SDR",
  "STS",
  "SRB",
  "SRA",
  "RSA",
  "SDH",
  "SSL",
  "SRL",
  "SCU",
  "SCL",
  "SCQ",
  "SON",
  "SDQ",
  "SLZ",
  "SAO",
  "CGH",
  "VCP",
  "TMS",
  "SPK",
  "OKD",
  "SJJ",
  "SKX",
  "SRQ",
  "YXE",
  "ZSS",
  "SAV",
  "SVL",
  "TAB",
  "NSO",
  "SCF",
  "SEA",
  "SEB",
  "SJY",
  "PKW",
  "SDJ",
  "SEL",
  "SVQ",
  "SFA",
  "ZTM",
  "SHA",
  "PVG",
  "SNN",
  "SHJ",
  "SSH",
  "SZD",
  "SHD",
  "SHE",
  "SZX",
  "SHR",
  "SHV",
  "JHQ",
  "SBW",
  "SDY",
  "SLS",
  "SIP",
  "MPD",
  "SIN",
  "QPG",
  "XSP",
  "SIX",
  "SUX",
  "FSD",
  "SIS",
  "SIT",
  "VAS",
  "SEW",
  "SGY",
  "KDU",
  "JSI",
  "SKP",
  "SKS",
  "SZK",
  "SXL",
  "YYD",
  "SOT",
  "SGD",
  "SFJ",
  "SOF",
  "SOG",
  "SOU",
  "SBN",
  "XSI",
  "SOI",
  "SEN",
  "SPU",
  "GEG",
  "SBU",
  "SPI",
  "SGF",
  "SXR",
  "YIF",
  "STX",
  "EBU",
  "SGU",
  "YYT",
  "STL",
  "UVF",
  "SXM",
  "SFG",
  "LED",
  "FSP",
  "STT",
  "SCE",
  "SVG",
  "HDN",
  "SZZ",
  "STO",
  "ARN",
  "BMA",
  "SCK",
  "SYY",
  "SXB",
  "KBY",
  "STR",
  "SUL",
  "SKZ",
  "LSI",
  "SUN",
  "SDL",
  "MCY",
  "SUB",
  "STV",
  "SWP",
  "SYD",
  "ZYL",
  "SYR",
  "TUU",
  "TIF",
  "TPE",
  "TAY",
  "TYN",
  "TAK",
  "TKA",
  "TLH",
  "QUF",
  "TLL",
  "TPA",
  "TMP",
  "TAM",
  "TMW",
  "TNG",
  "TRO",
  "TGV",
  "TAS",
  "TWU",
  "TBS",
  "TEU",
  "MME",
  "TGU",
  "THR",
  "TEQ",
  "TLV",
  "TEX",
  "TEM",
  "TCI",
  "TCA",
  "TER",
  "THE",
  "TMZ",
  "YXT",
  "HUF",
  "TXK",
  "TCU",
  "YQD",
  "TVF",
  "JTR",
  "TRV",
  "TED",
  "YTH",
  "KTB",
  "YQT",
  "TIS",
  "TSN",
  "TIJ",
  "TOD",
  "TIA",
  "TRZ",
  "TIV",
  "TKS",
  "TYO",
  "HND",
  "NRT",
  "TOL",
  "TPR",
  "TWB",
  "YTZ",
  "YYZ",
  "YTO",
  "TOV",
  "TOU",
  "TLS",
  "TSV",
  "TOY",
  "TZX",
  "TPS",
  "TVC",
  "TCB",
  "TTN",
  "TSF",
  "TRI",
  "TRS",
  "TIP",
  "TOS",
  "TRD",
  "TSB",
  "TUS",
  "TUP",
  "TUL",
  "TUN",
  "TUK",
  "TRN",
  "TKU",
  "TCL",
  "TGZ",
  "TWF",
  "TYR",
  "UAH",
  "UAP",
  "UBJ",
  "UBA",
  "UDI",
  "UBP",
  "UDR",
  "UDE",
  "UTH",
  "UFA",
  "UHE",
  "UGO",
  "UPG",
  "UCT",
  "UKI",
  "ULN",
  "UUD",
  "HLH",
  "ULB",
  "USN",
  "ULD",
  "UME",
  "YUD",
  "UTT",
  "UNK",
  "UNI",
  "UNT",
  "UPL",
  "JUV",
  "UTN",
  "UPP",
  "YBE",
  "UGC",
  "URM",
  "OMH",
  "UPN",
  "URB",
  "URG",
  "URC",
  "URZ",
  "USH",
  "UTP",
  "UCA",
  "UII",
  "UMD",
  "UDJ",
  "VAA",
  "VXO",
  "EGE",
  "YVO",
  "VDZ",
  "VLD",
  "VLC",
  "VLN",
  "VLL",
  "VAP",
  "VDE",
  "VAN",
  "YVR",
  "VRA",
  "VNS",
  "VRK",
  "VAR",
  "VST",
  "VLU",
  "VCE",
  "VER",
  "VEL",
  "VRB",
  "VRN",
  "YYJ",
  "VFA",
  "VID",
  "VTE",
  "VGO",
  "VSA",
  "VNO",
  "VIJ",
  "VIS",
  "VBY",
  "VIT",
  "VIX",
  "VYD",
  "YWK",
  "ACT",
  "WGA",
  "ALW",
  "WLS",
  "WVB",
  "WMB",
  "WAW",
  "IAD",
  "DCA",
  "WAS",
  "ALO",
  "ATY",
  "CWA",
  "WEI",
  "WEL",
  "WLG",
  "EAT",
  "PBI",
  "WYS",
  "GWT",
  "WHK",
  "YXN",
  "WRE",
  "HPN",
  "YXY",
  "HAP",
  "WYA",
  "SPS",
  "ICT",
  "WIC",
  "WHM",
  "VIE",
  "WIE",
  "AVP",
  "IPT",
  "ISL",
  "ILM",
  "WUN",
  "ERS",
  "WDH",
  "YQG",
  "YWG",
  "OLF",
  "WOL",
  "UMR",
  "ORH",
  "WRL",
  "WRG",
  "WUH",
  "WYN",
  "XMN",
  "XIY",
  "YKM",
  "YAK",
  "YKS",
  "GAJ",
  "ASK",
  "YNB",
  "YAO",
  "YZF",
  "SVX",
  "YIH",
  "YOK",
  "YUM",
  "ZCL",
  "ZAD",
  "ZAG",
  "ZTH",
  "ZAZ",
  "PZH",
  "ZND",
  "OUZ",
  "ZRH",
];

export type AirportIATACode = (typeof AirportIATACode)[number];

export const airportNameMap: Record<AirportIATACode, string> = {
  AAR: "Aarhus",
  ABD: "Abadan",
  AEH: "Abeche",
  ABZ: "Aberdeen",
  ABR: "Aberdeen (SD)",
  ABJ: "Abidjan",
  ABI: "Abilene (TX)",
  AUH: "Abu Dhabi - Abu Dhabi International",
  ABV: "Abuja - Nnamdi Azikiwe International Airport",
  AUE: "Abu Rudeis",
  ABS: "Abu Simbel",
  ACA: "Acapulco",
  ACC: "Accra - Kotoka International Airport",
  ADA: "Adana",
  ADD: "Addis Ababa - Bole International Airport",
  ADL: "Adelaide",
  ADE: "Aden - Aden International Airport",
  ADF: "Adiyaman",
  AER: "Adler/Sochi",
  AJY: "Agades",
  AGA: "Agadir",
  SUM: "Agana (Hagåtña)",
  AGZ: "Aggeneys",
  BQN: "Aguadilla",
  AGU: "Aguascaliente",
  AMD: "Ahmedabad",
  AYU: "Aiyura",
  AJA: "Ajaccio",
  AXT: "Akita",
  CAK: "Akron (OH)",
  AKT: "Akrotiri - RAF",
  AAN: "Al Ain",
  AAC: "Al Arish",
  ALH: "Albany",
  ABY: "Albany (GA)",
  ALB: "Albany (NY) - Albany International Airport",
  LBI: "Albi",
  AAL: "Alborg",
  ABQ: "Albuquerque (NM)",
  ABX: "Albury",
  ACI: "Alderney",
  ALP: "Aleppo",
  AES: "Alesund",
  ALJ: "Alexander Bay - Kortdoorn",
  HBH: "Alexandria - Borg el Arab Airport",
  ALY: "Alexandria - El Nhouza Airport",
  ESF: "Alexandria - Esler Field",
  FJR: "Alfujairah (Fujairah)",
  AHO: "Alghero Sassari",
  ALG: "Algiers, Houari Boumediene Airport",
  AHU: "Al Hoceima",
  ALC: "Alicante",
  ASP: "Alice Springs",
  ADY: "Alldays",
  ABE: "Allentown (PA)",
  ALA: "Almaty (Alma Ata) - Almaty International Airport",
  LEI: "Almeria",
  ALF: "Alta",
  AAT: "Altay",
  ACH: "Altenrhein",
  AOO: "Altoona (PA)",
  AXS: "Altus",
  ASJ: "Amami",
  AMA: "Amarillo (TX)",
  AZB: "Amazon Bay",
  AMM: "Amman - Queen Alia International Airport",
  ADJ: "Amman - Amman-Marka International Airport",
  ATQ: "Amritsar",
  AMS: "Amsterdam - Amsterdam Airport Schiphol",
  QNB: "Anand",
  ANC: "Anchorage (AK) - Ted Stevens Anchorage International",
  AOI: "Ancona - Ancona Falconara Airport",
  ALV: "Andorra La Vella - Heliport",
  AXA: "Anguilla",
  AJN: "Anjouan - Anjouan Airport",
  ANK: "Ankara",
  ESB: "Ankara - Esenboğa International Airport",
  AAE: "Annaba",
  ARB: "Ann Arbor (MI)",
  NCY: "Annecy",
  ANB: "Anniston (AL)",
  AYT: "Antalya",
  TNR: "Antananarivo (Tanannarive) - Ivato International Airport",
  ANU: "Antigua, V.C. Bird International",
  ANR: "Antwerp",
  AOJ: "Aomori",
  APW: "Apia - Faleolo International Airport",
  ATW: "Appelton/Neenah/Menasha (WI)",
  AQJ: "Aqaba",
  AJU: "Aracaju",
  ARH: "Arkhangelsk",
  ARK: "Arusha",
  GPA: "Araxos",
  RLT: "Arlit",
  ACE: "Arrecife/Lanzarote",
  AUA: "Aruba - Reina Beatrix International, Oranjestad",
  AVL: "Asheville (NC)",
  ASB: "Ashgabat - Saparmurat Turkmenbashy Int. Airport",
  ASM: "Asmara - Asmara International",
  ASE: "Aspen, (CO) - Aspen-Pitkin County Airport",
  ATZ: "Assiut",
  TSE: "Astana - Astana International Airport",
  ASU: "Asuncion - Asunción International Airport",
  ASW: "Aswan - Daraw Airport",
  ATH: "Athens - Elefthérios Venizélos International Airport",
  HEW: "Athens, Hellinikon Airport",
  AHN: "Athens (GA)",
  ATO: "Athens (OH)",
  ATL: "Atlanta (GA) - Hartsfield Atlanta International Airport",
  ACY: "Atlantic City (NJ) - Atlantic City International",
  YAT: "Attawapiskat, NT",
  AKL: "Auckland - Auckland International Airport",
  AGB: "Augsburg - Augsbur gAirport",
  AGS: "Augusta (GA)",
  AUG: "Augusta (ME) - Augusta State Airport",
  AUR: "Aurillac",
  AUS: "Austin (TX) - Austin-Bergstrom Airport",
  AYW: "Ayawasi",
  AYQ: "Ayers Rock - Connellan",
  AYR: "Ayr",
  BJZ: "Badajoz",
  BGW: "Bagdad - Baghdad International Airport",
  IXB: "Bagdogra",
  NAS: "Bahamas - Lynden Pindling International Airport",
  BHV: "Bahawalpur",
  BAH: "Bahrain - Bahrain International Airport",
  BFL: "Bakersfield (CA)",
  BAK: "Baku - Heydar Aliyev International Airport",
  BNK: "Ballina",
  BWI: "Baltimore (MD) - Washington International Airport",
  ABM: "Bamaga",
  BKO: "Bamako - Bamako-Sénou International Airport",
  BBY: "Bambari",
  BWN: "Bandar Seri Begawan - Brunei International Airport",
  BDO: "Bandung - Husein Sastranegara International Airport",
  BLR: "Bangalore",
  BGU: "Bangassou",
  DMK: "Bangkok, Don Muang",
  BKK: "Bangkok, Suvarnabhumi International",
  BGR: "Bangor (ME)",
  BGF: "Bangui - M'Poko International Airport",
  BJL: "Banjul - Banjul International Airport (Yundum International)",
  BNP: "Bannu",
  BCN: "Barcelona",
  BLA: "Barcelona",
  BDU: "Bardufoss",
  BRI: "Bari",
  BZL: "Barisal",
  BDQ: "Baroda",
  BRR: "Barra (the famous tidal beach landing)",
  BAQ: "Barranquilla",
  BSL: "Basel",
  EAP: "Basel/Mulhouse",
  BSR: "Basra, Basrah",
  PTP: "Basse-Terre - Pointe-à-Pitre International Airport",
  SKB: "Basseterre - Robert L. Bradshaw International Airport",
  BIA: "Bastia",
  BTR: "Baton Rouge (LA) - Baton Rouge Metropolitan Airport",
  BYU: "Bayreuth - Bindlacher-Berg",
  BPT: "Beaumont/Pt. Arthur (TX)",
  BKW: "Beckley (WV)",
  EIS: "Beef Island - Terrance B. Lettsome",
  PEK: "Beijing",
  NAY: "Beijing - Nanyuan Airport",
  BEW: "Beira",
  BEY: "Beirut - Beirut Rafic Hariri International Airport",
  BEL: "Belem - Val de Cans International Airport",
  BHD: "Belfast - George Best Belfast City Airport",
  BFS: "Belfast - Belfast International Airport",
  IXG: "Belgaum",
  BEG: "Belgrad (Beograd) - Belgrade Nikola Tesla International",
  BZE: "Belize City - Philip S.W.Goldson International",
  BLI: "Bellingham (WA)",
  CNF: "Belo Horizonte - Tancredo Neves International Airport",
  BJI: "Bemidji (MN)",
  BEB: "Benbecula",
  BEN: "Benghazi (Bengasi)",
  BUG: "Benguela",
  BEH: "Benton Harbour (MI)",
  BBT: "Berberati",
  BGY: "Bergamo/Milan - Orio Al Serio",
  BGO: "Bergen",
  EGC: "Bergerac - Roumanieres",
  BER: "Berlin",
  SXF: "Berlin, Schoenefeld",
  TXL: "Berlin, Tegel",
  THF: "Berlin, Tempelhof (ceased operating in 2008)",
  BDA: "Bermuda - L.F. Wade International Airport",
  BRN: "Berne, Bern-Belp",
  ZDJ: "Berne, Railway Service",
  BET: "Bethel (AK)",
  BHO: "Bhopal",
  BBI: "Bhubaneswar",
  BIQ: "Biarritz",
  BIO: "Bilbao",
  BIL: "Billings (MT)",
  BLL: "Billund",
  BTU: "Bintulu",
  IRO: "Biraro",
  BHX: "Birmingham - Birmingham International Airport",
  BHM: "Birmingham (AL)",
  FRU: "Bishkek - Manas International Airport",
  BIS: "Bismarck (ND) - Bismarck Municipal Airport",
  BXO: "Bissau - Osvaldo Vieiro International Airport",
  BLK: "Blackpool",
  BLT: "Blackwater",
  BLZ: "Blantyre (Mandala) - Chileka International Airport",
  BHE: "Blenheim",
  BFN: "Bloemfontein - Bloemfontein Airport",
  BMI: "Bloomington (IL)",
  BMG: "Bloomington (IN)",
  BLF: "Bluefield (WV)",
  BVB: "Boa Vista",
  BOY: "Bobo/Dioulasso",
  BOO: "Bodo",
  BJV: "Bodrum - Milas Airport",
  BOG: "Bogota - El Nuevo Dorado International Airport",
  BOI: "Boise (ID) - Boise Air Terminal",
  BLQ: "Bologna",
  BOM: "Bombay (Mumbai) - Chhatrapati Shivaji International",
  BON: "Bonaire",
  YVB: "Bonaventure, PQ",
  BOB: "Bora Bora",
  BOD: "Bordeaux - Bordeaux Airport",
  BXS: "Borrego Springs (CA)",
  BOS: "Boston (MA) - General Edward Lawrence Logan",
  BYK: "Bouake",
  BOJ: "Bourgas/Burgas",
  BOH: "Bournemouth",
  ZBO: "Bowen",
  BZN: "Bozeman (MT)",
  BFD: "Bradford/Warren (PA) /Olean (NY)",
  BRD: "Brainerd (MN)",
  BMP: "Brampton Island",
  BSB: "Brasilia - President Juscelino Kubitschek International",
  BTS: "Bratislava - M. R. Štefánik Airport",
  BZV: "Brazzaville - Maya-Maya Airport",
  BRE: "Bremen - Bremen Airport (Flughafen Bremen)",
  VBS: "Brescia, Montichiari",
  BES: "Brest",
  BIV: "Bria",
  BDR: "Bridgeport (CT)",
  BGI: "Bridgetown - Grantley Adams International",
  BDS: "Brindisi",
  BNE: "Brisbane",
  BRS: "Bristol",
  BNN: "Broennoeysund",
  BHQ: "Broken Hill",
  BKX: "Brookings (SD)",
  BME: "Broome",
  BQK: "Brunswick (GA)",
  BRU: "Brussels - Brussels Airport",
  BGA: "Bucaramanga",
  BUH: "Bucharest",
  OTP: "Bucharest - Henri Coandă International Airport",
  BUD: "Budapest - Budapest Ferihegy International Airport",
  BUE: "Buenos Aires",
  EZE: "Buenos Aires, Ezeiza International Airport",
  AEP: "Buenos Aires, Jorge Newbery",
  BFO: "Buffalo Range",
  BUF: "Buffalo/Niagara Falls (NY)",
  BJM: "Bujumbura - Bujumbura International Airport",
  BUQ: "Bulawayo",
  BHC: "Bullhead City (NV)",
  BDB: "Bundaberg",
  BUR: "Burbank (CA)",
  BRL: "Burlington IA",
  BTV: "Burlington (VT)",
  BWT: "Burnie (Wynyard)",
  BTM: "Butte (MT)",
  CAB: "Cabinda",
  CAG: "Cagliari",
  CNS: "Cairns",
  CAI: "Cairo - Cairo International Airport",
  CJC: "Calama - El Loa",
  CCU: "Calcutta (Kolkata) - Netaji Subhas Chandra",
  YYC: "Calgary - Calgary International Airport",
  CLO: "Cali",
  CCJ: "Calicut",
  CLY: "Calvi",
  YCB: "Cambridge Bay",
  CBG: "Cambrigde",
  CAL: "Campbeltown",
  CGR: "Campo Grande",
  CBR: "Canberra - Canberra Airport",
  CUN: "Cancun",
  CEQ: "Cannes – Mandelieu Airport",
  CIW: "Canouan (island) - Canouan Airport",
  CPT: "Cape Town - Cape Town International Airport",
  CCS: "Caracas - Simón Bolívar International Airport",
  CWL: "Cardiff - Cardiff Airport",
  CLD: "Carlsbad (CA)",
  CVQ: "Carnarvon",
  CRF: "Carnot",
  CSN: "Carson City (NV)",
  CAS: "Casablanca",
  CMN: "Casablanca, Mohamed V",
  LRM: "Casa de Campo - La Romana International Airport",
  CSI: "Casino",
  CPR: "Casper (WY)",
  CST: "Castaway",
  CTG: "Cartagena - Rafael Núñez International Airport",
  SLU: "Castries - George F. L. Charles Airport",
  CTA: "Catania",
  CAY: "Cayenne - Cayenne-Rochambeau Airport",
  CBU: "Cottbus - Cottbus-Drewitz Airport",
  CEB: "Cebu City - Mactan-Cebu International",
  CDC: "Cedar City (UT)",
  CID: "Cedar Rapids IA",
  CED: "Ceduna",
  CES: "Cessnock",
  KHV: "Chabarovsk (Khabarovsk)",
  CMF: "Chambery",
  CMI: "Champaign (IL)",
  IXC: "Chandigarh - Chandigarh International Airport",
  CGQ: "Changchun",
  CHQ: "Chania",
  CHG: "Chaoyang, Beijing - Chaoyang Airport",
  CHS: "Charleston (SC)",
  CRW: "Charleston (WV) - Yeager Airport",
  CLT: "Charlotte (NC)",
  CHO: "Charlottesville (VA)",
  CXT: "Charters Towers",
  CHA: "Chattanooga (TN)",
  CTU: "Chengdu - Shuangliu",
  MAA: "Chennai (Madras)",
  CYS: "Cheyenne (WY) - Cheyenne Regional Airport",
  CNX: "Chiang Mai - Chiang Mai International Airport",
  QCB: "Chiba City",
  MDW: "Chicago (IL), Midway",
  ORD: "Chicago (IL), O'Hare International Airport",
  CHI: "Chicago (IL)",
  CZA: "Chichen Itza",
  CIC: "Chico (CA)",
  CUU: "Chihuahua - Gen Fierro Villalobos",
  JKH: "Chios",
  CIP: "Chipata",
  KIV: "Chisinau - Chişinău International Airport",
  HTA: "Chita (Tschita)",
  CTS: "Sapporo - New Chitose Airport",
  CJL: "Chitral",
  CGP: "Chittagong",
  CKG: "Chongqing - Jiangbei International Airport",
  CHC: "Christchurch",
  CCZ: "Chub Cay",
  YYQ: "Churchill",
  CFG: "Cienfuegos - Jaime González Airport",
  CVG: "Cincinnati (OH) - Cincinnati/Northern Kentucky Int'l",
  CME: "Ciudad Del Carmen",
  CGU: "Ciudad Guayana",
  CJS: "Ciudad Juarez",
  CEN: "Ciudad Obregon",
  CVM: "Ciudad Victoria",
  CKB: "Clarksburg (WV)",
  CMQ: "Clermont",
  CFE: "Clermont Ferrand",
  BKL: "Cleveland (OH) , Burke Lakefront",
  CLE: "Cleveland (OH) - Cleveland Hopkins International",
  CBB: "Cochabamba",
  COK: "Cochin",
  COD: "Cody/Powell/Yellowstone (WY)",
  KCC: "Coffmann Cove (AK)",
  CFS: "Coffs Harbour",
  CJB: "Coimbatore",
  CLQ: "Colima",
  CLL: "College Station/Bryan (TX)",
  KCE: "Collinsville",
  CGN: "Cologne - Cologne Airport (Flughafen Köln/Bonn)",
  CMB: "Colombo - Bandaranaike International Airport",
  COS: "Colorado Springs (CO)",
  CAE: "Columbia (SC) - Columbia Metropolitan Airport",
  CSG: "Columbus (GA)",
  CMH: "Columbus (OH) - Port Columbus International",
  CKY: "Conakry - Conakry International Airport",
  CCR: "Concord (CA) - Buchanan Field",
  CON: "Concord (NH) - Concord Municipal Airport",
  CZL: "Constantine",
  CND: "Constanta (Constanța) - Constanta Int'l Airport",
  CPD: "Coober Pedy",
  CTN: "Cooktown",
  OOM: "Cooma",
  CPH: "Copenhagen - Copenhagen Airport",
  COR: "Cordoba",
  ODB: "Cordoba",
  CDV: "Cordova (AK)",
  CFU: "Corfu",
  ORK: "Cork",
  CRP: "Corpus Christi (TX)",
  COO: "Cotonou - Cotonou Cadjehoun Airport",
  CVT: "Coventry - Baginton",
  CZM: "Cozmel",
  CGA: "Craig (AK)",
  CEC: "Crescent City (CA)",
  CGB: "Cuiaba - Marechal Rondon International Airport",
  CUL: "Culiacan",
  CUR: "Curacao - Curaçao International Airport",
  CWB: "Curitiba - Afonso Pena International Airport",
  CYU: "Cuyo",
  DKR: "Dakar - Léopold Sédar Senghor International Airport",
  DLM: "Dalaman",
  DBY: "Dalby",
  DLC: "Dalian - Zhoushuizi International Airport",
  DAL: "Dallas (TX) , Love Field",
  DFW: "Dallas/Ft. Worth (TX) - Dallas/Fort Worth International",
  DJO: "Daloa",
  DAM: "Damascus, International",
  DMM: "Dammam, King Fahad International",
  DAN: "Danville (VA)",
  DAR: "Dar es Salam (Daressalam) - Julius Nyerere Int'l",
  DRW: "Darwin",
  DDI: "Daydream Island",
  DAY: "Dayton (OH)",
  DAB: "Daytona Beach (FL)",
  DEC: "Decatur (IL)",
  YDF: "Deer Lake/Corner Brook",
  DEL: "Delhi - Indira Gandhi International Airport",
  HAG: "Den Haag (The Hague)",
  DNZ: "Denizli",
  DPS: "Denpasar/Bali",
  DEN: "Denver (CO) - Denver International Airport",
  DSK: "Dera Ismail Khan - Dera Ismail Khan Airport",
  DRB: "Derby",
  LDY: "Derry (Londonderry)",
  DSM: "Des Moines (IA) - Des Moines International Airport",
  DET: "Detroit (MI) , Coleman A. Young Municipal",
  DTW: "Detroit (MI) , Wayne County Airport",
  DTT: "Detroit (MI) , Metropolitan Area",
  DVL: "Devils Lake (ND)",
  DPO: "Devonport",
  DHA: "Dhahran",
  DAC: "Dhaka - Zia International Airport",
  DIL: "Dili - Nicolau Lobato International Airport",
  DLG: "Dillingham (AK)",
  DNR: "Dinard",
  DLP: "Disneyland Paris",
  DJE: "Djerba",
  JIB: "Djibouti (city) - Djibouti-Ambouli International Airport",
  DOD: "Dodoma - Dodoma Airport",
  DOH: "Doha - Doha International Airport",
  DSA: "Doncaster/Sheffield, Robin Hood International Airport",
  CFN: "Donegal (Carrickfin)",
  DTM: "Dortmund",
  DHN: "Dothan (AL)",
  DLA: "Douala",
  DRS: "Dresden - Dresden Airport",
  DXB: "Dubai - Dubai International Airport",
  DBO: "Dubbo",
  DUB: "Dublin - Dublin International Airport",
  DUJ: "Dubois (PA)",
  DBV: "Dubrovnik",
  DBQ: "Dubuque IA",
  DUS: "Duesseldorf - Düsseldorf International Airport",
  DLH: "Duluth (MN) /Superior (WI)",
  DND: "Dundee",
  DUD: "Dunedin",
  DKI: "Dunk Island",
  DRO: "Durango (CO)",
  DUR: "Durban",
  DYU: "Dushanbe (Duschanbe) - Dushanbe Airport",
  DUT: "Dutch Harbor (AK)",
  DYA: "Dysart",
  DZA: "Dzaoudzi",
  ELS: "East London",
  IPC: "Easter Island",
  EAU: "Eau Clarie (WI)",
  EDI: "Edinburgh - Edinburgh Airport",
  YEA: "Edmonton",
  YEG: "Edmonton, International",
  YXD: "Edmonton, Municipal",
  EGS: "Egilsstadir",
  EIN: "Eindhoven",
  AZS: "Samana - Samaná El Catey International Airport",
  EBA: "Elba Island, Marina Di Campo",
  ETH: "Elat",
  VDA: "Elat, Ovula",
  EKI: "Elkhart (IN)",
  EKO: "Elko (NV)",
  ELL: "Ellisras",
  EMY: "El Minya",
  ELM: "Elmira (NY)",
  ELP: "El Paso (TX) - El Paso International Airport",
  ELY: "Ely (NV)",
  EDR: "Emerald",
  EMD: "Emerald",
  ENF: "Enontekioe",
  EBB: "Entebbe - Entebbe International Airport",
  ERF: "Erfurt - Erfurt Airport (Flughafen Erfurt)",
  ERI: "Erie (PA)",
  EVN: "Eriwan (Yerevan, Jerevan)",
  ERC: "Erzincan",
  ERZ: "Erzurum",
  EBJ: "Esbjerg",
  ESC: "Escanaba (MI)",
  EPR: "Esperance",
  EUG: "Eugene (OR)",
  ACV: "Eureka (CA)",
  EVV: "Evansville (IN)",
  EVE: "Evenes",
  EXT: "Exeter",
  FAI: "Fairbanks (AK)",
  FIE: "Fair Isle (Shetland)",
  LYP: "Faisalabad",
  FAR: "Fargo (ND) (MN)",
  FMN: "Farmington (NM)",
  FAO: "Faro",
  FAE: "Faroer - Vágar Airport",
  FYV: "Fayetteville (AR)",
  FAY: "Fayetteville/Ft. Bragg (NC)",
  FEZ: "Fes",
  FSC: "Figari",
  FLG: "Flagstaff (AZ)",
  YFO: "Flin Flon",
  FNT: "Flint (MI)",
  FLR: "Florence (Firenze) - Peretola Airport",
  FLO: "Florence (SC)",
  FLN: "Florianopolis",
  FRO: "Floro",
  YFA: "Fort Albert",
  FOR: "Fortaleza - Pinto Martins Airport",
  FDF: "Fort de France - Martinique Aimé Césaire International",
  FOD: "Fort Dodge IA",
  FHU: "Fort Huachuca/Sierra Vista (AZ)",
  FLL: "Fort Lauderdale/Hollywood (FL)",
  YMM: "Fort McMurray",
  FMY: "Fort Myers, Metropolitan Area (FL)",
  RSW: "Fort Myers, Southwest Florida Reg (FL)",
  FRI: "Fort Riley (KS) - Marshall AAF",
  YSM: "Fort Smith",
  FSM: "Fort Smith (AR)",
  YXJ: "Fort St. John",
  VPS: "Fort Walton Beach (FL)",
  FWA: "Fort Wayne (IN)",
  FOU: "Foula (Shetland)",
  FRW: "Francistown",
  FRA: "Frankfurt/Main - Frankfurt Airport (Rhein-Main-Flughafen)",
  HHN: "Frankfurt/Hahn",
  FKL: "Franklin/Oil City (PA)",
  YFC: "Fredericton",
  FPO: "Freeport - Grand Bahama International Airport",
  FNA: "Freetown - Freetown-Lungi International Airport",
  FRJ: "Frejus",
  FAT: "Fresno (CA)",
  FDH: "Friedrichshafen - Bodensee-Airport Friedrichshafen",
  FUE: "Fuerteventura",
  FUK: "Fukuoka",
  FKS: "Fukushima - Fukushima Airport",
  FNC: "Funchal",
  FUT: "Futuna",
  GBE: "Gaborone - Sir Seretse Khama International Airport",
  GAD: "Gadsden (AL)",
  GNV: "Gainesville (FL)",
  GWY: "Galway",
  YQX: "Gander",
  GOU: "Garoua",
  GZA: "Gaza City - Gaza International Airport",
  GZT: "Gaziantep",
  GDN: "Gdansk",
  GEX: "Geelong",
  GVA: "Geneva - Geneva-Cointrin International Airport",
  GOA: "Genoa",
  GRJ: "George",
  GEO: "Georgetown - Cheddi Jagan International Airport",
  GET: "Geraldton",
  GRO: "Gerona",
  GNE: "Ghent (Gent)",
  GIB: "Gibraltar",
  GCC: "Gilette (WY)",
  GIL: "Gilgit",
  YGX: "Gillam",
  GLT: "Gladstone",
  PIK: "Glasgow, Prestwick",
  GLA: "Glasgow",
  GGW: "Glasgow (MT)",
  GDV: "Glendive (MT)",
  GOI: "Goa",
  GYN: "Goiania, Santa Genoveva Airport",
  OOL: "Gold Coast",
  GOO: "Goondiwindi",
  YYR: "Goose Bay",
  GOZ: "Gorna",
  GOT: "Gothenburg (Göteborg) - Landvetter",
  GOV: "Gove (Nhulunbuy)",
  GHB: "Govenors Harbour",
  GRX: "Granada",
  GCN: "Grand Canyon (AZ)",
  GCM: "Grand Cayman - Owen Roberts International",
  GFK: "Grand Forks (ND)",
  GJT: "Grand Junction (CO)",
  GRR: "Grand Rapids (MI)",
  GPZ: "Grand Rapids (MN)",
  GRZ: "Graz",
  GTF: "Great Falls (MT)",
  GKL: "Great Keppel Island",
  GRB: "Green Bay (WI)",
  LWB: "Greenbrier/Lewisburg (WV)",
  GSO: "Greensboro/Winston Salem (NC)",
  GLH: "Greenville (MS)",
  PGV: "Greenville (NC)",
  GSP: "Greenville/Spartanburg (SC)",
  GND: "Grenada - Point Salines Airport also Maurice Bishop",
  GNB: "Grenoble",
  GFF: "Griffith",
  GRQ: "Groningen - Eelde",
  GTE: "Groote Eylandt - Alyangula",
  GON: "Groton/New London (CT)",
  GDL: "Guadalajara",
  GSI: "Guadalcanal",
  GUM: "Guam",
  CAN: "Guangzhou (Canton) - Baiyun International Airport",
  GRU: "Sao Paulo - Guarulhos International",
  GUA: "Guatemala City - La Aurora International Airport",
  GYE: "Guayaquil - Simon Bolivar",
  GCI: "Guernsey",
  GTI: "Guettin",
  GPT: "Gulfport/Biloxi (MS)",
  KWL: "Guilin - Liangjiang",
  ULU: "Gulu",
  GUC: "Gunnison/Crested Butte (CO)",
  GAU: "Guwahati",
  GWD: "Gwadar",
  GWE: "Gweru",
  GYP: "Gympie",
  HAC: "Hachijo Jima",
  HFA: "Haifa",
  HNS: "Haines (AK)",
  HKD: "Hakodate",
  YHZ: "Halifax International",
  YUX: "Hall Beach",
  HAM: "Hamburg - Fuhlsbuettel",
  HLT: "Hamilton",
  YHM: "Hamilton",
  HLZ: "Hamilton",
  HTI: "Hamilton Island",
  HFT: "Hammerfest",
  CMX: "Hancock (MI)",
  HGH: "Hangchow (Hangzhou)",
  HAJ: "Hannover",
  HAN: "Hanoi - Noi Bai International Airport",
  HRE: "Harare - Harare International Airport",
  HRB: "Harbin (Haerbin)",
  HRL: "Harlingen/South Padre Island (TX)",
  YHR: "Harrington Harbour, PQ",
  HAR: "Harrisburg (PA) - Harrisburg Skyport",
  MDT: "Harrisburg (PA) - Harrisburg International",
  BDL: "Hartford (CT) /Springfield (MA)",
  HDY: "Hatyai (Hat Yai)",
  HAU: "Haugesund",
  HAV: "Havana - José Martí International",
  HVR: "Havre (MT)",
  HIS: "Hayman Island",
  HLN: "Helena (MT)",
  JHE: "Helsingborg",
  HEL: "Helsinki - Vantaa",
  HER: "Heraklion",
  HMO: "Hermosillo - Gen. Pesqueira Garcia",
  HVB: "Hervey Bay",
  HIB: "Hibbing (MN)",
  HKY: "Hickory (NC)",
  ITO: "Hilo (HI)",
  HHH: "Hilton Head Island (SC)",
  HNK: "Hinchinbrook Island",
  HIJ: "Hiroshima International",
  SGN: "Ho Chi Minh City (Saigon) - Tan Son Nhat International",
  HBA: "Hobart",
  HOQ: "Hof",
  HOG: "Holguin",
  HMH: "Home Hill",
  HOM: "Homer (AK)",
  HKG: "Hong Kong - International Airport (HKIA)",
  ZJK: "Hong Kong - Chek Lap Kok",
  HIR: "Honiara Henderson International",
  HNL: "Honolulu (HI) - Honolulu International Airport",
  HNH: "Hoonah (AK)",
  HOR: "Horta",
  HOU: "Houston (TX) , Hobby",
  IAH: "Houston, TX - George Bush Intercontinental Airport",
  HUH: "Huahine",
  HUX: "Huatulco",
  HUI: "Hue - Phu Bai",
  HUY: "Humberside",
  HTS: "Huntington (WV)",
  HSV: "Huntsville (AL)",
  HRG: "Hurghada International",
  HON: "Huron (SD)",
  HWN: "Hwange National Park",
  HYA: "Hyannis (MA)",
  HYG: "Hydaburg (AK)",
  HYD: "Hyderabad - Rajiv Gandhi International Airport",
  HDD: "Hyderabad",
  IBZ: "Ibiza",
  IDA: "Idaho Falls (ID)",
  IGR: "Iguazu, Cataratas",
  ILP: "Ile des Pins",
  IOU: "Ile Ouen",
  ILI: "Iliamna (AK)",
  IPL: "Imperial (CA)",
  IVC: "Incercargill",
  ICN: "Incheon, Incheon International Airport",
  IND: "Indianapolis (IN) International",
  IGH: "Ingham",
  IFL: "Innisfail",
  INN: "Innsbruck - Kranebitten",
  INL: "International Falls (MN)",
  YEV: "Inuvik",
  INV: "Inverness",
  IYK: "Inykern (CA)",
  YFB: "Iqaluit (Frobisher Bay)",
  IQT: "Iquitos",
  IKT: "Irkutsk",
  ISG: "Ishigaki - New Ishigaki Airport",
  ISB: "Islamabad - Benazir Bhutto International Airport",
  ILY: "Islay",
  IOM: "Isle of Man",
  IST: "Istanbul - Istanbul Atatürk Airport",
  SAW: "Istanbul - Sabiha Gokcen",
  ITH: "Ithaca/Cortland (NY)",
  IVL: "Ivalo",
  ZIH: "Ixtapa/Zihuatenejo",
  IZM: "Izmir",
  ADB: "Izmir - Adnan Menderes Airport",
  JAC: "Jackson Hole (WY)",
  JXN: "Jackson (MI) - Reynolds Municipal",
  MJQ: "Jackson, MN",
  JAN: "Jackson (MS) - Jackson Internationall",
  HKS: "Jackson (MS) - Hawkins Field",
  MKL: "Jackson (TN) - Mckellar",
  LRF: "Jacksonville (AR) Little Rock AFB",
  NZC: "Jacksonville (FL) - Cecil Field NAS",
  NIP: "Jacksonville (FL) Jacksonville NAS",
  JAX: "Jacksonville (FL) - International",
  CRG: "Jacksonville (FL) - Craig Municipal",
  IJX: "Jacksonville (IL) - Municipal Airport",
  OAJ: "Jacksonville (NC)",
  JKV: "Jacksonville (TX)",
  JAK: "Jacmel",
  JAG: "Jacobabad",
  JCM: "Jacobina",
  JAQ: "Jacquinot Bay",
  JAF: "Jaffna - Kankesanturai",
  JGB: "Jagdalpur",
  JAI: "Jaipur - Sanganeer",
  JSA: "Jaisalmer",
  HLP: "Jakarta - Halim Perdana Kusuma",
  JKT: "Jakarta - Metropolitan Area",
  CGK: "Jakarta - Soekarno-Hatta International",
  JAA: "Jalalabad",
  JLR: "Jalandhar",
  JAL: "Jalapa",
  JLS: "Jales",
  UIT: "Jaluit Island",
  JMB: "Jamba",
  DJB: "Jambi - Sultan Taha Syarifudn",
  JAM: "Jambol",
  JMS: "Jamestown (ND)",
  JHW: "Jamestown (NY)",
  IXJ: "Jammu - Satwari",
  JGA: "Jamnagar - Govardhanpur",
  IXW: "Jamshedpur - Sonari Airport",
  JKR: "Janakpur",
  JAD: "Jandakot",
  JVL: "Janesville (WI) - Rock County",
  JNA: "Januaria",
  JQE: "Jaque",
  JTI: "Jatai",
  JAU: "Jauja",
  DJJ: "Jayapura - Sentani",
  JED: "Jeddah - King Abdulaziz International",
  JEF: "Jefferson City (MO) - Jefferson Memorial",
  JEE: "Jeremie - Jeremie Airport",
  XRY: "Jerez de la Frontera/Cadiz - La Parra",
  JER: "Jersey",
  JRS: "Jerusalem - Atarot Airport (closed)",
  JSR: "Jessore - Jessore Airport",
  PYB: "Jeypore - Jeypore Airport",
  JGS: "Ji'an",
  JMU: "Jiamusi - Jiamusi Airport",
  JGN: "Jiayuguan - Jiayuguan Airport",
  GJL: "Jijel",
  JIJ: "Jijiga",
  JIL: "Jilin",
  JIM: "Jimma",
  TNA: "Jinan",
  JDZ: "Jingdezhen",
  JHG: "Jinghong - Gasa Airport",
  JNG: "Jining",
  JIN: "Jinja",
  JJN: "Jinjiang",
  BCO: "Jinka - Baco/Jinka Airport",
  JNZ: "Jinzhou - Jinzhou Airport",
  JIP: "Jipijapa",
  JIR: "Jiri",
  JIU: "Jiujiang - Jiujiang Lushan Airport",
  JIW: "Jiwani",
  JCB: "Joacaba",
  JPA: "Joao Pessoa - Castro Pinto Airport",
  JDH: "Jodhpur",
  JKG: "Jönköping (Jonkoping) - Axamo Airport",
  JOE: "Joensuu",
  JNB: "Johannesburg - OR Tambo International Airport",
  BGM: "Johnson City (NY) - Binghamton/Endicott/Johnson",
  JON: "Johnston Island",
  JST: "Johnstown (PA)",
  JHB: "Johor Bahru - Sultan Ismail International",
  JOI: "Joinville - Cubatao Airport",
  JOL: "Jolo",
  JMO: "Jomsom",
  JBR: "Jonesboro (AR) Jonesboro Airport",
  JLN: "Joplin (MO)",
  JRH: "Jorhat - Rowriah Airport",
  JOS: "Jos",
  JSM: "Jose De San Martin",
  AJF: "Jouf",
  JJI: "Juanjui",
  JUB: "Juba",
  JUI: "Juist (island)",
  JDF: "Juiz De Fora - Francisco De Assis Airport",
  JUJ: "Jujuy - El Cadillal Airport",
  JCK: "Julia Creek",
  JUL: "Juliaca",
  JUM: "Jumla",
  JUN: "Jundah",
  JNU: "Juneau (AK) - Juneau International Airport",
  JNI: "Junin",
  JUT: "Juticalpa",
  JWA: "Jwaneng",
  JYV: "Jyväskylä (Jyvaskyla)",
  KBL: "Kabul - Khwaja Rawash Airport",
  KOJ: "Kagoshima",
  KCM: "Kahramanmaras",
  OGG: "Kahului (HI)",
  KAJ: "Kajaani",
  KLX: "Kalamata",
  AZO: "Kalamazoo/Battle Creek (MI)",
  KGI: "Kalgoorlie",
  KGD: "Kaliningrad",
  FCA: "Kalispell (MT)",
  KLR: "Kalmar",
  YKA: "Kamloops, BC",
  MUE: "Kamuela (HI)",
  KAN: "Kano",
  KNU: "Kanpur",
  MCI: "Kansas City (MO) - Kansas City International Airport",
  KHH: "Kaohsiung International",
  JHM: "Kapalua West (HI)",
  KHI: "Karachi - Jinnah International Airport",
  FKB: "Karlsruhe-Baden - Soellingen",
  KSD: "Karlstad",
  AOK: "Karpathos",
  KTA: "Karratha",
  KYS: "Kars",
  KRB: "Karumba",
  KRP: "Karup",
  ZKE: "Kaschechawan, PQ",
  KSL: "Kassala",
  KTR: "Katherine",
  KTM: "Kathmandu - Tribhuvan International Airport",
  MPA: "Katima Mulilo/Mpacha",
  KHJ: "Kauhajoki",
  MKK: "Kaunakakai (HI)",
  KVA: "Kavalla",
  ASR: "Kayseri",
  KZN: "Kazan - Kazan International Airport",
  KMP: "Keetmanshoop",
  YLW: "Kelowna, BC",
  KEM: "Kemi/Tornio",
  ENA: "Kenai (AK)",
  MSE: "Kent (Manston) Kent International",
  KIR: "Kerry County",
  KTN: "Ketchikan (AK)",
  EYW: "Key West (FL)",
  AHB: "Khamis Mushayat",
  UVL: "Kharga - New Valley",
  HRK: "Kharkov",
  KRT: "Khartoum - Khartoum International Airport",
  KDD: "Khuzdar",
  KEL: "Kiel - Holtenau",
  KBP: "Kiev - Borispol",
  IEV: "Kiev - Zhulhany",
  KGL: "Kigali - Gregoire Kayibanda",
  JRO: "Kilimadjaro",
  ILE: "Killeem (TX)",
  KIM: "Kimberley",
  KNS: "King Island",
  AKN: "King Salomon (AK)",
  KGC: "Kingscote",
  KIN: "Kingston - Norman Manley",
  ISO: "Kingston (NC)",
  SVD: "Kingstown - E. T. Joshua Airport",
  FIH: "Kinshasa - N'Djili",
  CXI: "Kiritimati (island) - Cassidy International Airport",
  KKN: "Kirkenes",
  KIK: "Kirkuk",
  KOI: "Kirkwall (Orkney)",
  KRN: "Kiruna",
  FKI: "Kisangani",
  KTT: "Kittilä",
  KIW: "Kitwe",
  KLU: "Klagenfurt",
  LMT: "Klamath Fall (OR)",
  KLW: "Klawock (AK)",
  KLZ: "Kleinsee",
  NOC: "Knock",
  TYS: "Knoxville (TN)",
  UKB: "Kobe",
  KCZ: "Kochi",
  ADQ: "Kodiak (AK)",
  OHT: "Kohat",
  KOK: "Kokkola/Pietarsaari",
  KMQ: "Komatsu",
  KOA: "Kona (HI)",
  KYA: "Konya",
  HGO: "Korhogo",
  KGS: "Kos",
  BKI: "Kota Kinabalu",
  OTZ: "Kotzbue (AK)",
  KWM: "Kowanyama",
  KRK: "Krakow (Cracow) - John Paul II International Airport",
  KRS: "Kristiansand",
  KID: "Kristianstad",
  KSU: "Kristiansund",
  KUL: "Kuala Lumpur - International Airport",
  SZB: "Kuala Lumpur - Sultan Abdul Aziz Shah",
  KUA: "Kuantan",
  KCH: "Kuching",
  KMJ: "Kumamoto",
  KNX: "Kununurra",
  KUO: "Kuopio",
  KUH: "Kushiro",
  YVP: "Kuujjuaq (FortChimo)",
  YGW: "Kuujjuarapik",
  KAO: "Kuusamo",
  KWI: "Kuwait - Kuwait International",
  UKY: "Kyoto",
  LEK: "Labe",
  WLB: "Labouchere Bay (AK)",
  LBU: "Labuan",
  XLB: "Lac Brochet, MB",
  LCG: "La Coruna",
  LSE: "La Crosse (WI)",
  LAE: "Lae - Lae Nadzab Airport",
  LRH: "La Rochelle",
  LAF: "Lafayette (IN)",
  LFT: "Lafayette, La",
  LOS: "Lagos - Murtala Muhammed Airport",
  YGL: "La Grande",
  LHE: "Lahore",
  LCH: "Lake Charles (LA)",
  HII: "Lake Havasu City (AZ)",
  TVL: "Lake Tahoe (CA)",
  LKL: "Lakselv",
  LBQ: "Lambarene",
  SUF: "Lamezia Terme",
  LMP: "Lampedusa",
  LNY: "Lanai City (HI)",
  LNS: "Lancaster (PA)",
  LEQ: "Land's End",
  LGK: "Langkawi (islands)",
  LAI: "Lannion",
  HLA: "Lanseria",
  LAN: "Lansing (MI)",
  LPB: "La Paz - El Alto",
  LAP: "La Paz - Leon",
  LPP: "Lappeenranta",
  LAR: "Laramie (WY)",
  LRD: "Laredo (TX)",
  LCA: "Larnaca",
  LPA: "Las Palmas",
  LAS: "Las Vegas (NV)",
  LBE: "Latrobe (PA)",
  LST: "Launceston",
  PIB: "Laurel/Hattisburg (MS)",
  LVO: "Laverton",
  LAW: "Lawton (OK)",
  LZC: "Lazaro Cardenas",
  YLR: "Leaf Rapids",
  LEA: "Learmouth (Exmouth)",
  LEB: "Lebanon (NH)",
  LBA: "Leeds/Bradford",
  LER: "Leinster",
  LEJ: "Leipzig",
  LEY: "Lelystad",
  BJX: "Leon",
  LNO: "Leonora",
  LWK: "Lerwick/Tingwall (Shetland Islands)",
  LWS: "Lewiston (ID)",
  LWT: "Lewistown (MT)",
  LEX: "Lexington (KY)",
  LBV: "Libreville",
  LDK: "Lidkoeping",
  LGG: "Liege",
  LIF: "Lifou",
  LIH: "Lihue (HI)",
  LIL: "Lille - Lille Airport",
  LLW: "Lilongwe - Lilongwe International",
  LIM: "Lima - J Chavez International",
  QLI: "Limassol",
  LIG: "Limoges",
  LNK: "Lincoln (NE)",
  LDC: "Lindeman Island",
  LNZ: "Linz - Hoersching",
  LIQ: "Lisala",
  LIS: "Lisbon - Lisboa",
  LSY: "Lismore",
  LIT: "Little Rock (AR)",
  LPL: "Liverpool",
  LZR: "Lizard Island",
  LJU: "Ljubljana - Brnik",
  IRG: "Lockhart River",
  LFW: "Lome",
  YXU: "London",
  LON: "London Metropolitan Area",
  LCY: "London - City Airport",
  LGW: "London - Gatwick",
  LHR: "London - Heathrow",
  LTN: "London - Luton",
  STN: "London - Stansted",
  LGB: "Long Beach (CA)",
  LIJ: "Long Island (AK)",
  ISP: "Long Island, Islip (NY) - Mac Arthur",
  LRE: "Longreach",
  GGG: "Longview/Kilgore (TX)",
  LYR: "Longyearbyen - Svalbard",
  LTO: "Loreto",
  LRT: "Lorient",
  LAX: "Los Angeles (CA) - International",
  SJD: "Los Cabos",
  LMM: "Los Mochis",
  TFN: "Los Rodeos",
  LSZ: "Losinj - Losinj Arpt",
  LDE: "Lourdes/Tarbes",
  SDF: "Louisville (KY)",
  LAD: "Luanda - 4 de Fevereiro",
  LBB: "Lubbock (TX)",
  LKO: "Lucknow",
  LUD: "Luederitz",
  MLA: "Luga",
  LUG: "Lugano",
  LLA: "Lulea",
  FBM: "Lumbumbashi",
  LUN: "Lusaka - Lusaka International Airport",
  LUJ: "Lusisiki",
  LUX: "Luxembourg",
  LUM: "Luxi - Mangshi",
  LXR: "Luxor",
  LWO: "Lvov (Lwow, Lemberg)",
  LYX: "Lydd - Lydd International Airport",
  LYH: "Lynchburg (VA)",
  LYS: "Lyon - Lyon-Saint Exupéry Airport official website",
  LYO: "Lyons (KS) - Rice County Municipal",
  MST: "Maastricht/Aachen",
  MCP: "Macapa - Alberto Alcolumbre International Airport",
  MFM: "Macau - Macau International Airport",
  MCZ: "Maceio - Zumbi dos Palmares International Airport",
  MKY: "Mackay",
  MCN: "Macon (GA)",
  NOP: "Mactan Island - Nab",
  MED: "Madinah (Medina) - Mohammad Bin Abdulaziz",
  MSN: "Madison (WI) - Dane County Regional Airport",
  MAD: "Madrid - Barajas Airport",
  SEZ: "Mahe - Seychelles International",
  MAH: "Mahon",
  MTL: "Maitland",
  MJN: "Majunga",
  MZG: "Makung",
  SSG: "Malabo - Malabo International Airport",
  AGP: "Malaga",
  MLX: "Malatya",
  MLE: "Male - Velana International Airport",
  MYD: "Malindi",
  MMA: "Malmo (Malmoe)",
  MMX: "Malmo (Malmö) - Malmö Airport",
  MJC: "Man",
  MGA: "Managua - Augusto C Sandino",
  MAO: "Manaus - Eduardo Gomes International Airport",
  MAN: "Manchester",
  MHT: "Manchester (NH)",
  MDL: "Mandalay - Mandalay-Annisaton Airport",
  MFO: "Manguna",
  XMH: "Manihi",
  MNL: "Manila - Ninoy Aquino International",
  ZLO: "Manzanillo",
  MTS: "Manzini - Matsapha International",
  MPM: "Maputo - Maputo International",
  MDQ: "Mar del Plata",
  MAR: "Maracaibo - La Chinita International",
  MFQ: "Maradi",
  MTH: "Marathon (FL)",
  MQM: "Mardin",
  MEE: "Mare",
  MGH: "Margate",
  PMV: "Margerita",
  MBX: "Maribor",
  MHQ: "Mariehamn (Maarianhamina)",
  MVR: "Maroua",
  MQT: "Marquette (MI)",
  RAK: "Marrakesh - Menara Airport",
  RMF: "Marsa Alam",
  MUH: "Marsa Matrah (Marsa Matruh)",
  MRS: "Marseille - Marseille Provence Airport",
  MHH: "Marsh Harbour",
  MVY: "Martha's Vineyard (MA)",
  MRB: "Martinsburg (WV)",
  MBH: "Maryborough",
  MSU: "Maseru - Moshoeshoe International",
  MCW: "Mason City IA",
  MVZ: "Masvingo",
  MMJ: "Matsumoto, Nagano",
  MYJ: "Matsuyama",
  MTO: "Mattoon (IL)",
  MUB: "Maun",
  MAU: "Maupiti",
  MRU: "Mauritius - S.Seewoosagur Ram International",
  MAZ: "Mayaguez",
  MZT: "Mazatlan",
  MFE: "McAllen (TX)",
  MES: "Medan - Polania Int'l (now Soewondo AFB)",
  KNO: "Medan - Kualanamu International",
  MDE: "Medellin - José María Córdova International",
  MFR: "Medford (OR)",
  MKR: "Meekatharra",
  MEL: "Melbourne - Melbourne Airport (Tullamarine)",
  MLB: "Melbourne (FL)",
  DOM: "Melville Hall",
  MEM: "Memphis (TN)",
  MDZ: "Mendoza",
  MDC: "Manado",
  MCE: "Merced (CA)",
  MID: "Merida",
  MEI: "Meridian (MS)",
  MIM: "Merimbula",
  MEZ: "Messina",
  MTM: "Metlakatla (AK)",
  MZM: "Metz - Frescaty",
  ETZ: "Metz/Nancy Metz-Nancy-Lorraine",
  MXL: "Mexicali",
  MEX: "Mexico City - Mexico City International Airport",
  AZP: "Mexico City - Atizapan",
  NLU: "Mexico City - Santa Lucia",
  MFU: "Mfuwe",
  MIA: "Miami (FL)",
  MWD: "Mianwali",
  MMM: "Middlemount",
  MAF: "Midland/Odessa (TX)",
  MDY: "Midway Island - Sand Island Field",
  MIK: "Mikkeli",
  MIL: "Milan",
  LIN: "Milan - Linate",
  MXP: "Milan - Malpensa",
  MQL: "Mildura",
  MLS: "Miles City (MT)",
  MFN: "Milford Sound",
  MKE: "Milwaukee (WI)",
  MTT: "Minatitlan",
  MRV: "Mineralnye Vody",
  MSP: "Minneapolis - St. Paul International Airport (MN)",
  MOT: "Minot (ND)",
  MSQ: "Minsk, International",
  MYY: "Miri",
  QML: "Mirpur",
  MSO: "Missula (MT)",
  MHE: "Mitchell (SD)",
  MMY: "Miyako Jima (Ryuku Islands) - Hirara",
  KMI: "Miyazaki",
  MBM: "Mkambati",
  MFF: "Moanda",
  MOB: "Mobile (AL) - Pascagoula (MS)",
  MOD: "Modesto (CA)",
  MJD: "Moenjodaro",
  MGQ: "Mogadishu",
  OKU: "Mokuti",
  MLI: "Moline/Quad Cities (IL)",
  MBA: "Mombasa - Moi International",
  MIR: "Monastir",
  YQM: "Moncton",
  MLU: "Monroe (LA)",
  MLW: "Monrovia - Metropolitan Area",
  ROB: "Monrovia - Roberts International",
  MBJ: "Montego Bay - Sangster International",
  QGF: "Montenegro",
  MRY: "Monterey (CA)",
  MTY: "Monterrey - Gen. Mariano Escobedo",
  NTR: "Monterrey - Aeropuerto Del Norte",
  MVD: "Montevideo - Carrasco International Airport",
  MGM: "Montgomery (AL) - Montgomery Regional Airport",
  MPL: "Montpellier - Montpellier–Méditerranée Airport",
  YMQ: "Montreal",
  YUL: "Montreal - Dorval (Montréal-Trudeau)",
  YMX: "Montreal - Mirabel",
  MTJ: "Montrose/Tellruide (CO)",
  MOZ: "Moorea",
  MOV: "Moranbah",
  MRZ: "Moree",
  MLM: "Morelia",
  MGW: "Morgantown (WV)",
  HNA: "Morioka, Hanamaki",
  HAH: "Moroni - Prince Said Ibrahim",
  MYA: "Moruya",
  MOW: "Moscow - Metropolitan Area",
  DME: "Moscow - Domodedovo",
  SVO: "Moscow - Sheremetyevo",
  VKO: "Moscow - Vnukovo",
  MWH: "Moses Lake (WA)",
  MZY: "Mossel Bay",
  OMO: "Mostar",
  OSM: "Mosul",
  MJL: "Mouila",
  MQQ: "Moundou",
  GTN: "Mount Cook",
  MGB: "Mount Gambier",
  MMG: "Mount Magnet",
  ISA: "Mt. Isa",
  MCL: "Mt. McKinley (AK)",
  MUC: "Muenchen (Munich) - Franz Josef Strauss",
  FMO: "Muenster/Osnabrueck",
  MLH: "Mulhouse",
  MUX: "Multan",
  MJV: "Murcia",
  MMK: "Murmansk",
  MSR: "Mus",
  MCT: "Muscat - Seeb",
  MSL: "Muscle Shoals (AL)",
  MKG: "Muskegon (MI)",
  MFG: "Muzaffarabad",
  MVB: "Mvengue",
  JMK: "Mykonos",
  MYR: "Myrtle Beach (SC) - Myrtle Beach AFB",
  CRE: "Myrtle Beach (SC) - Grand Strand Airport",
  MYQ: "Mysore",
  MJT: "Mytilene (Lesbos)",
  MZF: "Mzamba",
  NAN: "Nadi",
  NGS: "Nagasaki",
  NGO: "Nagoya - Komaki AFB",
  NAG: "Nagpur",
  NBO: "Nairobi",
  NAJ: "Nakhichevan",
  NST: "Nakhon Si Thammarat",
  ENC: "Nancy",
  YSR: "Nanisivik",
  NNG: "Nanning",
  NTE: "Nantes - Nantes Atlantique Airport",
  ACK: "Nantucket (MA)",
  NAP: "Naples - Naples Capodichino Airport",
  APF: "Naples (FL)",
  NAA: "Narrabri",
  NRA: "Narrandera",
  UAK: "Narsarsuaq",
  BNA: "Nashville (TN)",
  NAT: "Natal - Augusto Severo International Airport",
  SUV: "Nausori",
  WNS: "Nawab Shah",
  JNX: "Naxos - Naxos Airport",
  NDJ: "N'Djamena",
  NLA: "N'Dola",
  NSN: "Nelson",
  NLP: "Nelspruit",
  MQP: "Nelspruit - Kruger Mpumalanga International Airport",
  NEV: "Nevis",
  EWN: "New Bern (NC)",
  HVN: "New Haven (CT)",
  MSY: "New Orleans, La",
  NQY: "Newquay",
  JFK: "New York - John F. Kennedy (NY)",
  LGA: "New York - LaGuardia (NY)",
  EWR: "New York - Newark (NJ)",
  NYC: "New York (NY)",
  SWF: "Newburgh (NY)",
  BEO: "Newcastle - Belmont",
  NTL: "Newcastle - Williamtown",
  NCL: "Newcastle",
  NCS: "Newcastle",
  ZNE: "Newman",
  PHF: "Newport News/Williamsburg (VA)",
  NGE: "N'Gaoundere",
  IAG: "Niagara Falls International",
  NIM: "Niamey",
  NCE: "Nice - Cote D'Azur Airport",
  NIC: "Nicosia",
  NLV: "Nikolaev",
  KIJ: "Niigata",
  FNI: "Nimes",
  INI: "Nis",
  GOJ: "Nizhny Novgorod - Strigino International Airport",
  OME: "Nome (AK)",
  NSA: "Noosa",
  NLK: "Norfolk Island",
  ORF: "Norfolk/Virginia Beach (VA)",
  YVQ: "Norman Wells",
  NRK: "Norrkoeping",
  OTH: "North Bend (OR)",
  ELH: "North Eleuthera",
  NWI: "Norwich",
  EMA: "Nottingham - East Midlands",
  NDB: "Nouadhibou",
  NKC: "Nouakchott",
  NOU: "Noumea",
  QND: "Novi Sad",
  OVB: "Novosibirsk - Tolmachevo Airport",
  NUE: "Nürnberg (Nuremberg)",
  NLD: "Nuevo Laredo",
  TBU: "Nuku'alofa - Fua'Amotu International",
  OAK: "Oakland (CA)",
  OAX: "Oaxaca - Xoxocotlan",
  ODE: "Odense",
  ODS: "Odessa",
  ORB: "Oerebro",
  OHD: "Ohrid",
  OIT: "Oita",
  OKJ: "Okayama",
  OKA: "Okinawa, Ryukyo Island - Naha",
  OKC: "Oklahoma City (OK) - Will Rogers World",
  OLB: "Olbia",
  OLP: "Olympic Dam",
  OMA: "Omaha (NE)",
  OND: "Ondangwa",
  ONT: "Ontario (CA)",
  ORN: "Oran (Ouahran)",
  OAG: "Orange",
  SNA: "Orange County (Santa Ana) (CA)",
  OMD: "Oranjemund",
  ORL: "Orlando Metropolitan Area (FL)",
  MCO: "Orlando - International Airport (FL)",
  ORS: "Orpheus Island",
  OSA: "Osaka, Metropolitan Area",
  ITM: "Osaka - Itami",
  KIX: "Osaka - Kansai International Airport",
  OSH: "Oshkosh (WI)",
  OSI: "Osijek",
  OSL: "Oslo - Oslo Airport, Gardermoen",
  FBU: "Oslo - Fornebu",
  TRF: "Oslo - Sandefjord",
  YOW: "Ottawa - Hull",
  ODA: "Ouadda",
  OZZ: "Ouarzazate",
  OUH: "Oudtshoorn",
  OUA: "Ouagadougou",
  OUD: "Oujda",
  OUL: "Oulu",
  OUK: "Out Skerries (Shetland)",
  OVD: "Oviedo",
  OWB: "Owensboro (KY)",
  OXR: "Oxnard (CA)",
  UVE: "Oyem",
  PAD: "Paderborn/Lippstadt",
  PAH: "Paducah (KY)",
  PGA: "Page/Lake Powell (AZ)",
  PPG: "Pago Pago",
  PKB: "Pakersburg (WV) /Marietta (OH)",
  PMO: "Palermo - Punta Raisi",
  PMI: "Palma de Mallorca",
  PMW: "Palmas",
  PMD: "Palmdale/Lancaster (CA)",
  PMR: "Palmerston North",
  PSP: "Palm Springs (CA)",
  PTY: "Panama City - Tocumen International",
  PFN: "Panama City (FL)",
  PJG: "Panjgur",
  PNL: "Pantelleria",
  PPT: "Papeete - Faaa",
  PFO: "Paphos",
  PBO: "Paraburdoo",
  PBM: "Paramaribo - Zanderij International",
  PAR: "Paris",
  CDG: "Paris - Charles de Gaulle",
  LBG: "Paris - Le Bourget",
  ORY: "Paris - Orly",
  PBH: "Paro",
  PSC: "Pasco (WA)",
  PSI: "Pasni",
  PAT: "Patna",
  PYX: "Pattaya",
  PUF: "Pau",
  PLN: "Pellston (MI)",
  PEN: "Penang International",
  PDT: "Pendelton (OR)",
  PNS: "Pensacola (FL)",
  PIA: "Peoria/Bloomington (IL)",
  PEI: "Pereira",
  PGF: "Perpignan",
  PER: "Perth International",
  PEG: "Perugia",
  PSR: "Pescara",
  PEW: "Peshawar",
  PSG: "Petersburg (AK)",
  PHW: "Phalaborwa",
  PHL: "Philadelphia (PA) - International",
  PNH: "Phnom Penh - Pochentong",
  PHX: "Phoenix (AZ) - Sky Harbor International",
  HKT: "Phuket",
  PIR: "Pierre (SD)",
  PZB: "Pietermaritzburg",
  PTG: "Pietersburg",
  NTY: "Pilanesberg/Sun City",
  PSA: "Pisa - Galileo Galilei",
  PIT: "Pittsburgh International Airport (PA)",
  PLB: "Plattsburgh (NY)",
  PBZ: "Plettenberg Bay",
  PIH: "Pocatello (ID)",
  TGD: "Podgorica",
  PNI: "Pohnpei",
  PNR: "Pointe Noire",
  PIS: "Poitiers - Biard",
  PSE: "Ponce",
  PDL: "Ponta Delgada",
  POR: "Pori",
  CLM: "Port Angeles (WA)",
  PAP: "Port au Prince",
  PUG: "Port Augusta",
  PLZ: "Port Elizabeth",
  POG: "Port Gentil",
  PHC: "Port Harcourt",
  PHE: "Port Hedland",
  PTJ: "Portland",
  PWM: "Portland (ME)",
  PDX: "Portland International (OR)",
  PLO: "Port Lincoln",
  PQQ: "Port Macquarie",
  YPN: "Port Menier, PQ",
  POM: "Port Moresby - Jackson Field",
  OPO: "Porto",
  POA: "Porto Alegre - Salgado Filho International Airport",
  POS: "Port of Spain - Piarco International",
  PSD: "Port Said",
  PXO: "Porto Santo",
  PVH: "Porto Velho",
  VLI: "Port Vila",
  POU: "Poughkeepsie (NY)",
  POZ: "Poznan, Lawica",
  PRG: "Prague - Václav Havel Airport (formerly Ruzyne)",
  RAI: "Praia - Nelson Mandela International Airport",
  PQI: "Presque Island (ME)",
  PRY: "Pretoria - Wonderboom Apt.",
  PVK: "Preveza/Lefkas",
  YXS: "Prince George",
  YPR: "Prince Rupert/Digby Island",
  PRN: "Pristina",
  PPP: "Prosperpine",
  PVD: "Providence (RI)",
  SCC: "Prudhoe Bay (AK)",
  PBC: "Puebla",
  PUB: "Pueblo (CO)",
  PXM: "Puerto Escondido",
  PZO: "Puerto Ordaz",
  POP: "Puerto Plata",
  PVR: "Puerto Vallarta",
  XPK: "Pukatawagan",
  PUY: "Pula",
  PUW: "Pullman (WA)",
  PNQ: "Pune",
  PUQ: "Punta Arenas - Presidente Carlos Ibáñez del Campo",
  PUJ: "Punta Cana - Punta Cana International",
  PUS: "Pu San (Busan) - Gimhae International Airport",
  FNJ: "Pyongyang - Sunan International Airport",
  YQB: "Quebec - Quebec International",
  UEE: "Queenstown",
  ZQN: "Queenstown",
  UET: "Quetta",
  TAO: "Qingdao",
  UIP: "Quimper",
  UIN: "Quincy (IL)",
  UIO: "Quito - Mariscal Sucre International Airport",
  RBA: "Rabat - Rabat-Salé Airport",
  RYK: "Rahim Yar Khan - Shaikh Zayed International Airport",
  RFP: "Raiatea",
  YOP: "Rainbow Lake, AB",
  RAJ: "Rajkot",
  RDU: "Raleigh/Durham (NC)",
  IXR: "Ranchi",
  RGI: "Rangiroa",
  RGN: "Rangoon (Yangon) - Mingaladon",
  RAP: "Rapid City (SD)",
  RAR: "Rarotonga",
  RKT: "Ras al Khaymah (Ras al Khaimah)",
  RAZ: "Rawala Kot",
  RWP: "Rawalpindi",
  RDG: "Reading (PA)",
  REC: "Recife - Guararapes-Gilberto Freyre International",
  RDD: "Redding (CA)",
  RDM: "Redmond (OR)",
  REG: "Reggio Calabria",
  YQR: "Regina",
  TFS: "Reina Sofia",
  RNS: "Rennes",
  RNO: "Reno (NV)",
  YRB: "Resolute Bay",
  REU: "Reus",
  REK: "Reykjavik - Metropolitan Area",
  KEF: "Reykjavik - Keflavik International",
  RHI: "Rhinelander (WI)",
  RHO: "Rhodos",
  RCB: "Richards Bay",
  RIC: "Richmond (VA)",
  RIX: "Riga",
  RJK: "Rijeka",
  RMI: "Rimini",
  RBR: "Rio Branco - Plácido de Castro International Airport",
  GIG: "Rio de Janeiro - Galeao",
  SDU: "Rio de Janeiro - Santos Dumont",
  RIO: "Rio de Janeiro",
  RUH: "Riyadh - King Khaled International",
  RNE: "Roanne",
  ROA: "Roanoke (VA)",
  RTB: "Roatan",
  RST: "Rochester (MN)",
  ROC: "Rochester (NY)",
  RSD: "Rock Sound",
  RKS: "Rock Springs (WY)",
  RFD: "Rockford (IL)",
  ROK: "Rockhampton",
  RKD: "Rockland (ME)",
  RWI: "Rocky Mount - Wilson (NC)",
  RDZ: "Rodez",
  RRG: "Rodrigues Island",
  RNN: "Roenne",
  ROM: "Rome",
  CIA: "Rome - Ciampino",
  FCO: "Rome - Fuimicino",
  RNB: "Ronneby",
  ROS: "Rosario",
  RVI: "Rostov-on-Don - Rostov-on-Don Airport",
  ROV: "Rostov-on-Don - Platov International Airport",
  ROT: "Rotorua",
  RTM: "Rotterdam",
  RVN: "Rovaniemi",
  NDU: "Rundu",
  ROU: "Ruse",
  SCN: "Saarbruecken",
  SMF: "Sacramento (CA)",
  SDS: "Sado Shima",
  MBS: "Saginaw/Bay City/Midland (MI)",
  SDT: "Saidu Sharif",
  SBK: "Saint Brieuc",
  RUN: "Saint Denis - Roland Garros Airport",
  YSJ: "Saint John",
  SPN: "Saipan",
  SID: "Sal",
  SLL: "Salalah",
  SLE: "Salem (OR)",
  SNS: "Salinas (CA)",
  SNC: "Salinas",
  SAY: "Salisbury",
  SBY: "Salisbury (MD)",
  SKG: "Saloniki",
  SLA: "Salta, Gen Belgrano",
  SLC: "Salt Lake City (UT)",
  SSA: "Salvador - Salvador International Airport",
  SZG: "Salzburg - W.A. Mozart",
  KUF: "Samara - Kurumoch International Airport",
  SKD: "Samarkand - Samarkand International Airport",
  SMI: "Samos",
  SZF: "Samsun",
  ADZ: "San Andres",
  SJT: "San Angelo (TX)",
  SAT: "San Antonio (TX)",
  BRC: "San Carlos de Bariloche",
  SAN: "San Diego - Lindberg Field International (CA)",
  SFO: "San Francisco - International Airport, SA",
  SJO: "San Jose",
  SJC: "San Jose (CA)",
  SJU: "San Juan - Luis Munoz Marin International Airport",
  SBP: "San Luis Obisco (CA)",
  SLP: "San Luis Potosi",
  SPY: "San Pedro",
  SAP: "San Pedro Sula",
  ZSA: "San Salvador",
  SAL: "San Salvador",
  EAS: "San Sebastian",
  SAH: "Sanaa (Sana'a) - Sana'a International",
  YZP: "Sandspit",
  SBA: "Santa Barbara (CA)",
  SPC: "Santa Cruz de la Palma",
  SRZ: "Santa Cruz de la Sierra",
  SKV: "Santa Katarina - Mount Sinai",
  SMA: "Santa Maria",
  SMX: "Santa Maria (CA)",
  SDR: "Santander",
  STS: "Santa Rosa (CA)",
  SRB: "Santa Rosa",
  SRA: "Santa Rosa",
  RSA: "Santa Rosa",
  SDH: "Santa Rosa, Copan",
  SSL: "Santa Rosalia",
  SRL: "Santa Rosalia",
  SCU: "Santiago - Antonio Maceo Airport",
  SCL: "Santiago de Chile - Arturo Merino Benitez",
  SCQ: "Santiago de Compostela",
  SON: "Santo",
  SDQ: "Santo Domingo",
  SLZ: "Sao Luis - Marechal Cunha Machado International",
  SAO: "Sao Paulo",
  CGH: "Sao Paulo - Congonhas",
  VCP: "Sao Paulo - Viracopos",
  TMS: "Sao Tome",
  SPK: "Sapporo",
  OKD: "Sapporo - Okadama",
  SJJ: "Sarajevo",
  SKX: "Saransk - Saransk Airport",
  SRQ: "Sarasota/Bradenton (FL)",
  YXE: "Saskatoon",
  ZSS: "Sassandra",
  SAV: "Savannah (GA)",
  SVL: "Savonlinna",
  TAB: "Scarborough - Crown Point International",
  NSO: "Scone",
  SCF: "Scottsdale (AZ)",
  SEA: "Seattle/Tacoma (WA)",
  SEB: "Sehba",
  SJY: "Seinaejoki",
  PKW: "Selibi Phikwe",
  SDJ: "Sendai",
  SEL: "Seoul - Kimpo",
  SVQ: "Sevilla",
  SFA: "Sfax",
  ZTM: "Shamattawa, MB",
  SHA: "Shanghai - Hongqiao",
  PVG: "Shanghai - Pu Dong",
  SNN: "Shannon (Limerick)",
  SHJ: "Sharjah",
  SSH: "Sharm El Sheikh",
  SZD: "Sheffield, City Airport",
  SHD: "Shenandoah Valley/Stauton (VA)",
  SHE: "Shenyang",
  SZX: "Shenzhen - Shenzhen Bao'an International",
  SHR: "Sheridan (WY)",
  SHV: "Shreveport, La",
  JHQ: "Shute Harbour",
  SBW: "Sibu",
  SDY: "Sidney (MT)",
  SLS: "Silistra",
  SIP: "Simferopol",
  MPD: "Sindhri",
  SIN: "Singapore - Changi",
  QPG: "Singapore - Paya Lebar",
  XSP: "Singapore - Seletar",
  SIX: "Singleton",
  SUX: "Sioux City IA",
  FSD: "Sioux Falls (SD)",
  SIS: "Sishen",
  SIT: "Sitka (AK)",
  VAS: "Sivas",
  SEW: "Siwa",
  SGY: "Skagway (AK)",
  KDU: "Skardu",
  JSI: "Skiathos",
  SKP: "Skopje",
  SKS: "Skrydstrup",
  SZK: "Skukuza",
  SXL: "Sligo",
  YYD: "Smithers",
  SOT: "Sodankylae",
  SGD: "Soenderborg",
  SFJ: "Soendre Stroemfjord",
  SOF: "Sofia - Vrazhdebna",
  SOG: "Sogndal",
  SOU: "Southampton - Eastleigh",
  SBN: "South Bend (IN)",
  XSI: "South Indian Lake, MB",
  SOI: "South Molle Island",
  SEN: "Southend (London)",
  SPU: "Split",
  GEG: "Spokane (WA)",
  SBU: "Springbok",
  SPI: "Springfield (IL)",
  SGF: "Springfield (MO)",
  SXR: "Srinagar",
  YIF: "St. Augustin, PQ",
  STX: "St. Croix",
  EBU: "St. Etienne",
  SGU: "St. George (UT)",
  YYT: "St. John's",
  STL: "St. Louis (MO) Lambert–St. Louis International Airport",
  UVF: "St. Lucia Hewanorra",
  SXM: "St. Marteen",
  SFG: "St. Martin",
  LED: "St. Petersburg (Leningrad) - Pulkovo",
  FSP: "St. Pierre, NF",
  STT: "St. Thomas",
  SCE: "State College/Belefonte (PA)",
  SVG: "Stavanger",
  HDN: "Steamboat Springs (CO)",
  SZZ: "Stettin",
  STO: "Stockholm Metropolitan Area",
  ARN: "Stockholm - Arlanda",
  BMA: "Stockholm - Bromma",
  SCK: "Stockton (CA)",
  SYY: "Stornway",
  SXB: "Strasbourg - Strasbourg Airport",
  KBY: "Streaky Bay",
  STR: "Stuttgart - Echterdingen",
  SUL: "Sui",
  SKZ: "Sukkur",
  LSI: "Sumburgh (Shetland)",
  SUN: "Sun Valley (ID)",
  SDL: "Sundsvall",
  MCY: "Sunshine Coast",
  SUB: "Surabaya - Juanda",
  STV: "Surat",
  SWP: "Swakopmund",
  SYD: "Sydney - Sydney Airport",
  ZYL: "Sylhet",
  SYR: "Syracuse (NY)",
  TUU: "Tabuk",
  TIF: "Taif",
  TPE: "Taipei - Chiang Kai Shek",
  TAY: "Taipei - Sung Shan",
  TYN: "Taiyuan",
  TAK: "Takamatsu",
  TKA: "Talkeetna (AK)",
  TLH: "Tallahassee (FL)",
  QUF: "Tallinn - Pirita Harbour",
  TLL: "Tallinn - Ulemiste",
  TPA: "Tampa - International (FL)",
  TMP: "Tampere",
  TAM: "Tampico - Gen. F. Javier Mina",
  TMW: "Tamworth",
  TNG: "Tangier - Boukhalef",
  TRO: "Taree",
  TGV: "Targovishte",
  TAS: "Tashkent - International",
  TWU: "Tawau",
  TBS: "Tbilisi - Novo Alexeyevka",
  TEU: "Te Anau",
  MME: "Teesside, Durham Tees Valley",
  TGU: "Tegucigalpa",
  THR: "Tehran (Teheran) - Mehrabad",
  TEQ: "Tekirdag - Corlu",
  TLV: "Tel Aviv - Ben Gurion International",
  TEX: "Telluride (CO)",
  TEM: "Temora",
  TCI: "Tenerife",
  TCA: "Tennant Creek",
  TER: "Terceira",
  THE: "Teresina",
  TMZ: "Termez (Termes)",
  YXT: "Terrace",
  HUF: "Terre Haute (IN)",
  TXK: "Texarkana (AR)",
  TCU: "Thaba'Nchu",
  YQD: "The Pas",
  TVF: "Thief River Falls (MN)",
  JTR: "Thira",
  TRV: "Thiruvananthapuram",
  TED: "Thisted",
  YTH: "Thompson",
  KTB: "Thorne Bay (AK)",
  YQT: "Thunder Bay",
  TIS: "Thursday Island",
  TSN: "Tianjin",
  TIJ: "Tijuana - Rodriguez",
  TOD: "Tioman",
  TIA: "Tirana - Rinas",
  TRZ: "Tiruchirapally",
  TIV: "Tivat",
  TKS: "Tokushima",
  TYO: "Tokyo",
  HND: "Tokyo - Haneda",
  NRT: "Tokyo - Narita",
  TOL: "Toledo (OH)",
  TPR: "Tom Price",
  TWB: "Toowoomba",
  YTZ: "Toronto - Billy Bishop Toronto City Airport",
  YYZ: "Toronto - Toronto Pearson International Airport",
  YTO: "Toronto",
  TOV: "Tortola",
  TOU: "Touho",
  TLS: "Toulouse - Blagnac Airport",
  TSV: "Townsville",
  TOY: "Toyama",
  TZX: "Trabzon",
  TPS: "Trapani",
  TVC: "Traverse City (MI)",
  TCB: "Treasure Cay",
  TTN: "Trenton/Princeton (NJ)",
  TSF: "Treviso",
  TRI: "Tri-Cities Regional (TN) /VA",
  TRS: "Trieste",
  TIP: "Tripoli - Tripoli International",
  TOS: "Tromsoe",
  TRD: "Trondheim",
  TSB: "Tsumeb",
  TUS: "Tucson (AZ)",
  TUP: "Tulepo (MS)",
  TUL: "Tulsa (OK)",
  TUN: "Tunis - Carthage",
  TUK: "Turbat",
  TRN: "Turin",
  TKU: "Turku",
  TCL: "Tuscaloosa (AL)",
  TGZ: "Tuxtla Gutierrez",
  TWF: "Twin Falls (ID)",
  TYR: "Tyler (TX)",
  UAH: "Ua Huka",
  UAP: "Ua Pou",
  UBJ: "Ube",
  UBA: "Uberaba",
  UDI: "Uberlandia - Eduardo Gomes Airport",
  UBP: "Ubon Ratchathani - Muang Ubon Airport",
  UDR: "Udaipur - Dabok Airport",
  UDE: "Uden - Volkel Airport",
  UTH: "Udon Thani",
  UFA: "Ufa",
  UHE: "Uherske Hradiste",
  UGO: "Uige",
  UPG: "Ujung Pandang - Hasanudin Airport",
  UCT: "Ukhta",
  UKI: "Ukiah (CA)",
  ULN: "Ulaanbaatar - Buyant Uhaa Airport",
  UUD: "Ulan-Ude",
  HLH: "Ulanhot",
  ULB: "Ulei",
  USN: "Ulsan",
  ULD: "Ulundi",
  UME: "Umea",
  YUD: "Umiujaq",
  UTT: "Umtata",
  UNK: "Unalakleet (AK)",
  UNI: "Union Island",
  UNT: "Unst (Shetland Island) - Baltasound Airport",
  UPL: "Upala",
  JUV: "Upernavik - Upernavik Heliport",
  UTN: "Upington",
  UPP: "Upolu Point (HI)",
  YBE: "Uranium City",
  UGC: "Urgench",
  URM: "Uriman",
  OMH: "Urmiehm (Orumieh)",
  UPN: "Uruapan",
  URB: "Urubupunga - Ernesto Pochler Airport",
  URG: "Uruguaiana - Ruben Berta Airport",
  URC: "Urumqi",
  URZ: "Uruzgan",
  USH: "Ushuaia - Islas Malvinas Airport",
  UTP: "Utapao (Pattaya)",
  UCA: "Utica (NY) - Oneida County Airport",
  UII: "Utila",
  UMD: "Uummannaq",
  UDJ: "Uzhgorod",
  VAA: "Vaasa",
  VXO: "Vaexjoe",
  EGE: "Vail (CO)",
  YVO: "Val d'Or",
  VDZ: "Valdez (AK)",
  VLD: "Valdosta (GA)",
  VLC: "Valencia",
  VLN: "Valencia",
  VLL: "Valladolid",
  VAP: "Valparaiso",
  VDE: "Valverde",
  VAN: "Van - Ferit Melen",
  YVR: "Vancouver - Vancouver International",
  VRA: "Varadero",
  VNS: "Varanasi",
  VRK: "Varkaus",
  VAR: "Varna",
  VST: "Vasteras",
  VLU: "Velikiye Luki (Welikije Luki)",
  VCE: "Venice - Marco Polo",
  VER: "Veracruz",
  VEL: "Vernal (UT)",
  VRB: "Vero Beach/Ft. Pierce (FL)",
  VRN: "Verona",
  YYJ: "Victoria",
  VFA: "Victoria Falls",
  VID: "Vidin",
  VTE: "Vientiane - Wattay",
  VGO: "Vigo",
  VSA: "Villahermosa",
  VNO: "Vilnius",
  VIJ: "Virgin Gorda",
  VIS: "Visalia (CA)",
  VBY: "Visby",
  VIT: "Vitoria",
  VIX: "Vitoria - Eurico de Aguiar Salles Airport",
  VYD: "Vryheid",
  YWK: "Wabush",
  ACT: "Waco (TX)",
  WGA: "Wagga",
  ALW: "Walla Walla (WA)",
  WLS: "Wallis",
  WVB: "Walvis Bay",
  WMB: "Warrnambool",
  WAW: "Warsaw - Frédéric Chopin",
  IAD: "Washington DC - Dulles International",
  DCA: "Washington DC - Ronald Reagan National",
  WAS: "Washington DC",
  ALO: "Waterloo IA",
  ATY: "Watertown (SD)",
  CWA: "Wausau/Stevens Point (WI)",
  WEI: "Weipa",
  WEL: "Welkom",
  WLG: "Wellington",
  EAT: "Wenatchee (WA)",
  PBI: "West Palm Beach (FL)",
  WYS: "West Yellowstone (MT)",
  GWT: "Westerland, Sylt Airport",
  WHK: "Whakatane",
  YXN: "Whale Cove, NT",
  WRE: "Whangarei",
  HPN: "White Plains (NY)",
  YXY: "Whitehorse",
  HAP: "Whitsunday Resort",
  WYA: "Whyalla",
  SPS: "Wichita Falls (TX)",
  ICT: "Wichita (KS)",
  WIC: "Wick",
  WHM: "Wickham",
  VIE: "Wien (Vienna) - Vienna International",
  WIE: "Wiesbaden, Air Base",
  AVP: "Wilkes Barre/Scranton (PA)",
  IPT: "Williamsport (PA)",
  ISL: "Williston (ND)",
  ILM: "Wilmington (NC)",
  WUN: "Wiluna",
  ERS: "Windhoek - Eros",
  WDH: "Windhoek - Hosea Kutako International",
  YQG: "Windsor Ontario",
  YWG: "Winnipeg International",
  OLF: "Wolf Point (MT)",
  WOL: "Wollongong",
  UMR: "Woomera",
  ORH: "Worcester (MA)",
  WRL: "Worland (WY)",
  WRG: "Wrangell (AK)",
  WUH: "Wuhan",
  WYN: "Wyndham",
  XMN: "Xiamen",
  XIY: "Xi'an - Xianyang",
  YKM: "Yakima (WA)",
  YAK: "Yakutat (AK)",
  YKS: "Yakutsk",
  GAJ: "Yamagata, Junmachi",
  ASK: "Yamoussoukro",
  YNB: "Yanbu",
  YAO: "Yaounde",
  YZF: "Yellowknife",
  SVX: "Yekaterinburg - Koltsovo Airport",
  YIH: "Yichang",
  YOK: "Yokohama",
  YUM: "Yuma (AZ)",
  ZCL: "Zacatecas",
  ZAD: "Zadar",
  ZAG: "Zagreb - Zagreb Airport Pleso",
  ZTH: "Zakynthos",
  ZAZ: "Zaragoza",
  PZH: "Zhob",
  ZND: "Zinder",
  OUZ: "Zouerate",
  ZRH: "Zurich (Zürich) - Kloten",
} as const;
