name: check

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run build
        run: pnpm build
